/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ForgetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForgetRequest{}

// ForgetRequest Cascading erasure of a root and its dependents. Operator-privileged; needs `canErase`.
type ForgetRequest struct {
	Mandate MemoryMandate `json:"mandate"`
	RootId string `json:"rootId"`
}

type _ForgetRequest ForgetRequest

// NewForgetRequest instantiates a new ForgetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForgetRequest(mandate MemoryMandate, rootId string) *ForgetRequest {
	this := ForgetRequest{}
	this.Mandate = mandate
	this.RootId = rootId
	return &this
}

// NewForgetRequestWithDefaults instantiates a new ForgetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForgetRequestWithDefaults() *ForgetRequest {
	this := ForgetRequest{}
	return &this
}

// GetMandate returns the Mandate field value
func (o *ForgetRequest) GetMandate() MemoryMandate {
	if o == nil {
		var ret MemoryMandate
		return ret
	}

	return o.Mandate
}

// GetMandateOk returns a tuple with the Mandate field value
// and a boolean to check if the value has been set.
func (o *ForgetRequest) GetMandateOk() (*MemoryMandate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mandate, true
}

// SetMandate sets field value
func (o *ForgetRequest) SetMandate(v MemoryMandate) {
	o.Mandate = v
}

// GetRootId returns the RootId field value
func (o *ForgetRequest) GetRootId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootId
}

// GetRootIdOk returns a tuple with the RootId field value
// and a boolean to check if the value has been set.
func (o *ForgetRequest) GetRootIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootId, true
}

// SetRootId sets field value
func (o *ForgetRequest) SetRootId(v string) {
	o.RootId = v
}

func (o ForgetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForgetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mandate"] = o.Mandate
	toSerialize["rootId"] = o.RootId
	return toSerialize, nil
}

func (o *ForgetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mandate",
		"rootId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForgetRequest := _ForgetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForgetRequest)

	if err != nil {
		return err
	}

	*o = ForgetRequest(varForgetRequest)

	return err
}

type NullableForgetRequest struct {
	value *ForgetRequest
	isSet bool
}

func (v NullableForgetRequest) Get() *ForgetRequest {
	return v.value
}

func (v *NullableForgetRequest) Set(val *ForgetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableForgetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableForgetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForgetRequest(val *ForgetRequest) *NullableForgetRequest {
	return &NullableForgetRequest{value: val, isSet: true}
}

func (v NullableForgetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForgetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


