/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DisclosureSignature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisclosureSignature{}

// DisclosureSignature The ed25519 signature over the canonicalized document.
type DisclosureSignature struct {
	Algorithm string `json:"algorithm"`
	// Signer's public key (hex). Equals document.agentId in the common case; under rotation it is the current key at the tip of rotation_chain. 
	PublicKey string `json:"public_key"`
	// Signature over the canonicalized document (hex).
	Value string `json:"value"`
}

type _DisclosureSignature DisclosureSignature

// NewDisclosureSignature instantiates a new DisclosureSignature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisclosureSignature(algorithm string, publicKey string, value string) *DisclosureSignature {
	this := DisclosureSignature{}
	this.Algorithm = algorithm
	this.PublicKey = publicKey
	this.Value = value
	return &this
}

// NewDisclosureSignatureWithDefaults instantiates a new DisclosureSignature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisclosureSignatureWithDefaults() *DisclosureSignature {
	this := DisclosureSignature{}
	return &this
}

// GetAlgorithm returns the Algorithm field value
func (o *DisclosureSignature) GetAlgorithm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Algorithm
}

// GetAlgorithmOk returns a tuple with the Algorithm field value
// and a boolean to check if the value has been set.
func (o *DisclosureSignature) GetAlgorithmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Algorithm, true
}

// SetAlgorithm sets field value
func (o *DisclosureSignature) SetAlgorithm(v string) {
	o.Algorithm = v
}

// GetPublicKey returns the PublicKey field value
func (o *DisclosureSignature) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *DisclosureSignature) GetPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *DisclosureSignature) SetPublicKey(v string) {
	o.PublicKey = v
}

// GetValue returns the Value field value
func (o *DisclosureSignature) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *DisclosureSignature) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *DisclosureSignature) SetValue(v string) {
	o.Value = v
}

func (o DisclosureSignature) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisclosureSignature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["algorithm"] = o.Algorithm
	toSerialize["public_key"] = o.PublicKey
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *DisclosureSignature) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"algorithm",
		"public_key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisclosureSignature := _DisclosureSignature{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDisclosureSignature)

	if err != nil {
		return err
	}

	*o = DisclosureSignature(varDisclosureSignature)

	return err
}

type NullableDisclosureSignature struct {
	value *DisclosureSignature
	isSet bool
}

func (v NullableDisclosureSignature) Get() *DisclosureSignature {
	return v.value
}

func (v *NullableDisclosureSignature) Set(val *DisclosureSignature) {
	v.value = val
	v.isSet = true
}

func (v NullableDisclosureSignature) IsSet() bool {
	return v.isSet
}

func (v *NullableDisclosureSignature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisclosureSignature(val *DisclosureSignature) *NullableDisclosureSignature {
	return &NullableDisclosureSignature{value: val, isSet: true}
}

func (v NullableDisclosureSignature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisclosureSignature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


