/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UsageSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageSummary{}

// UsageSummary Metered call counts for one principal over a half-open window. Counts only.
type UsageSummary struct {
	KeyId string `json:"keyId"`
	Since time.Time `json:"since"`
	Until time.Time `json:"until"`
	// Total calls counted in the window (after any tag filter).
	Total int32 `json:"total"`
	// Count keyed by operation, e.g. { pay: 3, resolve: 1 }.
	ByOperation map[string]int32 `json:"byOperation"`
	// Count keyed by outcome, e.g. { allow: 2, deny: 1 }.
	ByOutcome map[string]int32 `json:"byOutcome"`
}

type _UsageSummary UsageSummary

// NewUsageSummary instantiates a new UsageSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageSummary(keyId string, since time.Time, until time.Time, total int32, byOperation map[string]int32, byOutcome map[string]int32) *UsageSummary {
	this := UsageSummary{}
	this.KeyId = keyId
	this.Since = since
	this.Until = until
	this.Total = total
	this.ByOperation = byOperation
	this.ByOutcome = byOutcome
	return &this
}

// NewUsageSummaryWithDefaults instantiates a new UsageSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageSummaryWithDefaults() *UsageSummary {
	this := UsageSummary{}
	return &this
}

// GetKeyId returns the KeyId field value
func (o *UsageSummary) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *UsageSummary) SetKeyId(v string) {
	o.KeyId = v
}

// GetSince returns the Since field value
func (o *UsageSummary) GetSince() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Since
}

// GetSinceOk returns a tuple with the Since field value
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetSinceOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Since, true
}

// SetSince sets field value
func (o *UsageSummary) SetSince(v time.Time) {
	o.Since = v
}

// GetUntil returns the Until field value
func (o *UsageSummary) GetUntil() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Until
}

// GetUntilOk returns a tuple with the Until field value
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Until, true
}

// SetUntil sets field value
func (o *UsageSummary) SetUntil(v time.Time) {
	o.Until = v
}

// GetTotal returns the Total field value
func (o *UsageSummary) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *UsageSummary) SetTotal(v int32) {
	o.Total = v
}

// GetByOperation returns the ByOperation field value
func (o *UsageSummary) GetByOperation() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.ByOperation
}

// GetByOperationOk returns a tuple with the ByOperation field value
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetByOperationOk() (map[string]int32, bool) {
	if o == nil {
		return map[string]int32{}, false
	}
	return o.ByOperation, true
}

// SetByOperation sets field value
func (o *UsageSummary) SetByOperation(v map[string]int32) {
	o.ByOperation = v
}

// GetByOutcome returns the ByOutcome field value
func (o *UsageSummary) GetByOutcome() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.ByOutcome
}

// GetByOutcomeOk returns a tuple with the ByOutcome field value
// and a boolean to check if the value has been set.
func (o *UsageSummary) GetByOutcomeOk() (map[string]int32, bool) {
	if o == nil {
		return map[string]int32{}, false
	}
	return o.ByOutcome, true
}

// SetByOutcome sets field value
func (o *UsageSummary) SetByOutcome(v map[string]int32) {
	o.ByOutcome = v
}

func (o UsageSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keyId"] = o.KeyId
	toSerialize["since"] = o.Since
	toSerialize["until"] = o.Until
	toSerialize["total"] = o.Total
	toSerialize["byOperation"] = o.ByOperation
	toSerialize["byOutcome"] = o.ByOutcome
	return toSerialize, nil
}

func (o *UsageSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keyId",
		"since",
		"until",
		"total",
		"byOperation",
		"byOutcome",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageSummary := _UsageSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageSummary)

	if err != nil {
		return err
	}

	*o = UsageSummary(varUsageSummary)

	return err
}

type NullableUsageSummary struct {
	value *UsageSummary
	isSet bool
}

func (v NullableUsageSummary) Get() *UsageSummary {
	return v.value
}

func (v *NullableUsageSummary) Set(val *UsageSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageSummary(val *UsageSummary) *NullableUsageSummary {
	return &NullableUsageSummary{value: val, isSet: true}
}

func (v NullableUsageSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


