/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Mandate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Mandate{}

// Mandate Operator-granted, scoped, capped, expiring spend authority.
type Mandate struct {
	Id string `json:"id"`
	// Allowed counterparties (CAIP-10 where on-chain).
	Payees []string `json:"payees"`
	PerTxCap Amount `json:"per_tx_cap"`
	PerPeriodCap Amount `json:"per_period_cap"`
	// ISO-8601 duration for the period cap window.
	Period string `json:"period"`
	ExpiresAt time.Time `json:"expires_at"`
	Constraints map[string]interface{} `json:"constraints,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Mandate Mandate

// NewMandate instantiates a new Mandate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMandate(id string, payees []string, perTxCap Amount, perPeriodCap Amount, period string, expiresAt time.Time) *Mandate {
	this := Mandate{}
	this.Id = id
	this.Payees = payees
	this.PerTxCap = perTxCap
	this.PerPeriodCap = perPeriodCap
	this.Period = period
	this.ExpiresAt = expiresAt
	return &this
}

// NewMandateWithDefaults instantiates a new Mandate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMandateWithDefaults() *Mandate {
	this := Mandate{}
	return &this
}

// GetId returns the Id field value
func (o *Mandate) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Mandate) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Mandate) SetId(v string) {
	o.Id = v
}

// GetPayees returns the Payees field value
func (o *Mandate) GetPayees() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Payees
}

// GetPayeesOk returns a tuple with the Payees field value
// and a boolean to check if the value has been set.
func (o *Mandate) GetPayeesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Payees, true
}

// SetPayees sets field value
func (o *Mandate) SetPayees(v []string) {
	o.Payees = v
}

// GetPerTxCap returns the PerTxCap field value
func (o *Mandate) GetPerTxCap() Amount {
	if o == nil {
		var ret Amount
		return ret
	}

	return o.PerTxCap
}

// GetPerTxCapOk returns a tuple with the PerTxCap field value
// and a boolean to check if the value has been set.
func (o *Mandate) GetPerTxCapOk() (*Amount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerTxCap, true
}

// SetPerTxCap sets field value
func (o *Mandate) SetPerTxCap(v Amount) {
	o.PerTxCap = v
}

// GetPerPeriodCap returns the PerPeriodCap field value
func (o *Mandate) GetPerPeriodCap() Amount {
	if o == nil {
		var ret Amount
		return ret
	}

	return o.PerPeriodCap
}

// GetPerPeriodCapOk returns a tuple with the PerPeriodCap field value
// and a boolean to check if the value has been set.
func (o *Mandate) GetPerPeriodCapOk() (*Amount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerPeriodCap, true
}

// SetPerPeriodCap sets field value
func (o *Mandate) SetPerPeriodCap(v Amount) {
	o.PerPeriodCap = v
}

// GetPeriod returns the Period field value
func (o *Mandate) GetPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Period
}

// GetPeriodOk returns a tuple with the Period field value
// and a boolean to check if the value has been set.
func (o *Mandate) GetPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Period, true
}

// SetPeriod sets field value
func (o *Mandate) SetPeriod(v string) {
	o.Period = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *Mandate) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *Mandate) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *Mandate) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetConstraints returns the Constraints field value if set, zero value otherwise.
func (o *Mandate) GetConstraints() map[string]interface{} {
	if o == nil || IsNil(o.Constraints) {
		var ret map[string]interface{}
		return ret
	}
	return o.Constraints
}

// GetConstraintsOk returns a tuple with the Constraints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mandate) GetConstraintsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Constraints) {
		return map[string]interface{}{}, false
	}
	return o.Constraints, true
}

// HasConstraints returns a boolean if a field has been set.
func (o *Mandate) HasConstraints() bool {
	if o != nil && !IsNil(o.Constraints) {
		return true
	}

	return false
}

// SetConstraints gets a reference to the given map[string]interface{} and assigns it to the Constraints field.
func (o *Mandate) SetConstraints(v map[string]interface{}) {
	o.Constraints = v
}

func (o Mandate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Mandate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["payees"] = o.Payees
	toSerialize["per_tx_cap"] = o.PerTxCap
	toSerialize["per_period_cap"] = o.PerPeriodCap
	toSerialize["period"] = o.Period
	toSerialize["expires_at"] = o.ExpiresAt
	if !IsNil(o.Constraints) {
		toSerialize["constraints"] = o.Constraints
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Mandate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"payees",
		"per_tx_cap",
		"per_period_cap",
		"period",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMandate := _Mandate{}

	err = json.Unmarshal(data, &varMandate)

	if err != nil {
		return err
	}

	*o = Mandate(varMandate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "payees")
		delete(additionalProperties, "per_tx_cap")
		delete(additionalProperties, "per_period_cap")
		delete(additionalProperties, "period")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "constraints")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMandate struct {
	value *Mandate
	isSet bool
}

func (v NullableMandate) Get() *Mandate {
	return v.value
}

func (v *NullableMandate) Set(val *Mandate) {
	v.value = val
	v.isSet = true
}

func (v NullableMandate) IsSet() bool {
	return v.isSet
}

func (v *NullableMandate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMandate(val *Mandate) *NullableMandate {
	return &NullableMandate{value: val, isSet: true}
}

func (v NullableMandate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMandate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


