/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Order type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Order{}

// Order The completed result of buy(). Beta.
type Order struct {
	Id string `json:"id"`
	Status string `json:"status"`
	Receipt *Receipt `json:"receipt,omitempty"`
	Cart *Cart `json:"cart,omitempty"`
}

type _Order Order

// NewOrder instantiates a new Order object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrder(id string, status string) *Order {
	this := Order{}
	this.Id = id
	this.Status = status
	return &this
}

// NewOrderWithDefaults instantiates a new Order object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderWithDefaults() *Order {
	this := Order{}
	return &this
}

// GetId returns the Id field value
func (o *Order) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Order) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Order) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *Order) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Order) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Order) SetStatus(v string) {
	o.Status = v
}

// GetReceipt returns the Receipt field value if set, zero value otherwise.
func (o *Order) GetReceipt() Receipt {
	if o == nil || IsNil(o.Receipt) {
		var ret Receipt
		return ret
	}
	return *o.Receipt
}

// GetReceiptOk returns a tuple with the Receipt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetReceiptOk() (*Receipt, bool) {
	if o == nil || IsNil(o.Receipt) {
		return nil, false
	}
	return o.Receipt, true
}

// HasReceipt returns a boolean if a field has been set.
func (o *Order) HasReceipt() bool {
	if o != nil && !IsNil(o.Receipt) {
		return true
	}

	return false
}

// SetReceipt gets a reference to the given Receipt and assigns it to the Receipt field.
func (o *Order) SetReceipt(v Receipt) {
	o.Receipt = &v
}

// GetCart returns the Cart field value if set, zero value otherwise.
func (o *Order) GetCart() Cart {
	if o == nil || IsNil(o.Cart) {
		var ret Cart
		return ret
	}
	return *o.Cart
}

// GetCartOk returns a tuple with the Cart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Order) GetCartOk() (*Cart, bool) {
	if o == nil || IsNil(o.Cart) {
		return nil, false
	}
	return o.Cart, true
}

// HasCart returns a boolean if a field has been set.
func (o *Order) HasCart() bool {
	if o != nil && !IsNil(o.Cart) {
		return true
	}

	return false
}

// SetCart gets a reference to the given Cart and assigns it to the Cart field.
func (o *Order) SetCart(v Cart) {
	o.Cart = &v
}

func (o Order) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Order) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	if !IsNil(o.Receipt) {
		toSerialize["receipt"] = o.Receipt
	}
	if !IsNil(o.Cart) {
		toSerialize["cart"] = o.Cart
	}
	return toSerialize, nil
}

func (o *Order) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrder := _Order{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrder)

	if err != nil {
		return err
	}

	*o = Order(varOrder)

	return err
}

type NullableOrder struct {
	value *Order
	isSet bool
}

func (v NullableOrder) Get() *Order {
	return v.value
}

func (v *NullableOrder) Set(val *Order) {
	v.value = val
	v.isSet = true
}

func (v NullableOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrder(val *Order) *NullableOrder {
	return &NullableOrder{value: val, isSet: true}
}

func (v NullableOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


