/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssembledContextBudget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssembledContextBudget{}

// AssembledContextBudget struct for AssembledContextBudget
type AssembledContextBudget struct {
	MaxTokens int32 `json:"maxTokens"`
}

type _AssembledContextBudget AssembledContextBudget

// NewAssembledContextBudget instantiates a new AssembledContextBudget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssembledContextBudget(maxTokens int32) *AssembledContextBudget {
	this := AssembledContextBudget{}
	this.MaxTokens = maxTokens
	return &this
}

// NewAssembledContextBudgetWithDefaults instantiates a new AssembledContextBudget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssembledContextBudgetWithDefaults() *AssembledContextBudget {
	this := AssembledContextBudget{}
	return &this
}

// GetMaxTokens returns the MaxTokens field value
func (o *AssembledContextBudget) GetMaxTokens() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value
// and a boolean to check if the value has been set.
func (o *AssembledContextBudget) GetMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxTokens, true
}

// SetMaxTokens sets field value
func (o *AssembledContextBudget) SetMaxTokens(v int32) {
	o.MaxTokens = v
}

func (o AssembledContextBudget) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssembledContextBudget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maxTokens"] = o.MaxTokens
	return toSerialize, nil
}

func (o *AssembledContextBudget) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxTokens",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssembledContextBudget := _AssembledContextBudget{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssembledContextBudget)

	if err != nil {
		return err
	}

	*o = AssembledContextBudget(varAssembledContextBudget)

	return err
}

type NullableAssembledContextBudget struct {
	value *AssembledContextBudget
	isSet bool
}

func (v NullableAssembledContextBudget) Get() *AssembledContextBudget {
	return v.value
}

func (v *NullableAssembledContextBudget) Set(val *AssembledContextBudget) {
	v.value = val
	v.isSet = true
}

func (v NullableAssembledContextBudget) IsSet() bool {
	return v.isSet
}

func (v *NullableAssembledContextBudget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssembledContextBudget(val *AssembledContextBudget) *NullableAssembledContextBudget {
	return &NullableAssembledContextBudget{value: val, isSet: true}
}

func (v NullableAssembledContextBudget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssembledContextBudget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


