/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Audit200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Audit200Response{}

// Audit200Response struct for Audit200Response
type Audit200Response struct {
	Data []AuditEvent `json:"data"`
	// True when items remain after this page.
	HasMore bool `json:"has_more"`
	// Token for the next page, or null when `has_more` is false.
	NextCursor string `json:"next_cursor"`
}

type _Audit200Response Audit200Response

// NewAudit200Response instantiates a new Audit200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudit200Response(data []AuditEvent, hasMore bool, nextCursor string) *Audit200Response {
	this := Audit200Response{}
	this.Data = data
	this.HasMore = hasMore
	this.NextCursor = nextCursor
	return &this
}

// NewAudit200ResponseWithDefaults instantiates a new Audit200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudit200ResponseWithDefaults() *Audit200Response {
	this := Audit200Response{}
	return &this
}

// GetData returns the Data field value
func (o *Audit200Response) GetData() []AuditEvent {
	if o == nil {
		var ret []AuditEvent
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Audit200Response) GetDataOk() ([]AuditEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *Audit200Response) SetData(v []AuditEvent) {
	o.Data = v
}

// GetHasMore returns the HasMore field value
func (o *Audit200Response) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *Audit200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *Audit200Response) SetHasMore(v bool) {
	o.HasMore = v
}

// GetNextCursor returns the NextCursor field value
func (o *Audit200Response) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *Audit200Response) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *Audit200Response) SetNextCursor(v string) {
	o.NextCursor = v
}

func (o Audit200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Audit200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["has_more"] = o.HasMore
	toSerialize["next_cursor"] = o.NextCursor
	return toSerialize, nil
}

func (o *Audit200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"has_more",
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAudit200Response := _Audit200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAudit200Response)

	if err != nil {
		return err
	}

	*o = Audit200Response(varAudit200Response)

	return err
}

type NullableAudit200Response struct {
	value *Audit200Response
	isSet bool
}

func (v NullableAudit200Response) Get() *Audit200Response {
	return v.value
}

func (v *NullableAudit200Response) Set(val *Audit200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAudit200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAudit200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudit200Response(val *Audit200Response) *NullableAudit200Response {
	return &NullableAudit200Response{value: val, isSet: true}
}

func (v NullableAudit200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudit200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


