/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// Pay202Response - struct for Pay202Response
type Pay202Response struct {
	Decision *Decision
	PendingSettlement *PendingSettlement
}

// DecisionAsPay202Response is a convenience function that returns Decision wrapped in Pay202Response
func DecisionAsPay202Response(v *Decision) Pay202Response {
	return Pay202Response{
		Decision: v,
	}
}

// PendingSettlementAsPay202Response is a convenience function that returns PendingSettlement wrapped in Pay202Response
func PendingSettlementAsPay202Response(v *PendingSettlement) Pay202Response {
	return Pay202Response{
		PendingSettlement: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Pay202Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Decision
	err = newStrictDecoder(data).Decode(&dst.Decision)
	if err == nil {
		jsonDecision, _ := json.Marshal(dst.Decision)
		if string(jsonDecision) == "{}" { // empty struct
			dst.Decision = nil
		} else {
			if err = validator.Validate(dst.Decision); err != nil {
				dst.Decision = nil
			} else {
				match++
			}
		}
	} else {
		dst.Decision = nil
	}

	// try to unmarshal data into PendingSettlement
	err = newStrictDecoder(data).Decode(&dst.PendingSettlement)
	if err == nil {
		jsonPendingSettlement, _ := json.Marshal(dst.PendingSettlement)
		if string(jsonPendingSettlement) == "{}" { // empty struct
			dst.PendingSettlement = nil
		} else {
			if err = validator.Validate(dst.PendingSettlement); err != nil {
				dst.PendingSettlement = nil
			} else {
				match++
			}
		}
	} else {
		dst.PendingSettlement = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Decision = nil
		dst.PendingSettlement = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Pay202Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Pay202Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Pay202Response) MarshalJSON() ([]byte, error) {
	if src.Decision != nil {
		return json.Marshal(&src.Decision)
	}

	if src.PendingSettlement != nil {
		return json.Marshal(&src.PendingSettlement)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Pay202Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Decision != nil {
		return obj.Decision
	}

	if obj.PendingSettlement != nil {
		return obj.PendingSettlement
	}

	// all schemas are nil
	return nil
}

type NullablePay202Response struct {
	value *Pay202Response
	isSet bool
}

func (v NullablePay202Response) Get() *Pay202Response {
	return v.value
}

func (v *NullablePay202Response) Set(val *Pay202Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePay202Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePay202Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePay202Response(val *Pay202Response) *NullablePay202Response {
	return &NullablePay202Response{value: val, isSet: true}
}

func (v NullablePay202Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePay202Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


