/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// RailId A payment rail behind pay()/buy(). The only place vendor/protocol names appear.
type RailId string

// List of RailId
const (
	X402 RailId = "x402"
	MPP RailId = "mpp"
	AP2 RailId = "ap2"
	ACP RailId = "acp"
	UCP RailId = "ucp"
	CARD RailId = "card"
	ONCHAIN RailId = "onchain"
	L402 RailId = "l402"
)

// All allowed values of RailId enum
var AllowedRailIdEnumValues = []RailId{
	"x402",
	"mpp",
	"ap2",
	"acp",
	"ucp",
	"card",
	"onchain",
	"l402",
}

func (v *RailId) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RailId(value)
	for _, existing := range AllowedRailIdEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RailId", value)
}

// NewRailIdFromValue returns a pointer to a valid RailId
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRailIdFromValue(v string) (*RailId, error) {
	ev := RailId(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RailId: valid values are %v", v, AllowedRailIdEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RailId) IsValid() bool {
	for _, existing := range AllowedRailIdEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RailId value
func (v RailId) Ptr() *RailId {
	return &v
}

type NullableRailId struct {
	value *RailId
	isSet bool
}

func (v NullableRailId) Get() *RailId {
	return v.value
}

func (v *NullableRailId) Set(val *RailId) {
	v.value = val
	v.isSet = true
}

func (v NullableRailId) IsSet() bool {
	return v.isSet
}

func (v *NullableRailId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRailId(val *RailId) *NullableRailId {
	return &NullableRailId{value: val, isSet: true}
}

func (v NullableRailId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRailId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

