/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpoint{}

// WebhookEndpoint A registered delivery endpoint as the reads expose it (secret redacted).
type WebhookEndpoint struct {
	Id string `json:"id"`
	Url string `json:"url"`
	Events []WebhookEventType `json:"events"`
	Active bool `json:"active"`
}

type _WebhookEndpoint WebhookEndpoint

// NewWebhookEndpoint instantiates a new WebhookEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpoint(id string, url string, events []WebhookEventType, active bool) *WebhookEndpoint {
	this := WebhookEndpoint{}
	this.Id = id
	this.Url = url
	this.Events = events
	this.Active = active
	return &this
}

// NewWebhookEndpointWithDefaults instantiates a new WebhookEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointWithDefaults() *WebhookEndpoint {
	this := WebhookEndpoint{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookEndpoint) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpoint) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookEndpoint) SetId(v string) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *WebhookEndpoint) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpoint) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookEndpoint) SetUrl(v string) {
	o.Url = v
}

// GetEvents returns the Events field value
func (o *WebhookEndpoint) GetEvents() []WebhookEventType {
	if o == nil {
		var ret []WebhookEventType
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpoint) GetEventsOk() ([]WebhookEventType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookEndpoint) SetEvents(v []WebhookEventType) {
	o.Events = v
}

// GetActive returns the Active field value
func (o *WebhookEndpoint) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpoint) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *WebhookEndpoint) SetActive(v bool) {
	o.Active = v
}

func (o WebhookEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	toSerialize["events"] = o.Events
	toSerialize["active"] = o.Active
	return toSerialize, nil
}

func (o *WebhookEndpoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"events",
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEndpoint := _WebhookEndpoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEndpoint)

	if err != nil {
		return err
	}

	*o = WebhookEndpoint(varWebhookEndpoint)

	return err
}

type NullableWebhookEndpoint struct {
	value *WebhookEndpoint
	isSet bool
}

func (v NullableWebhookEndpoint) Get() *WebhookEndpoint {
	return v.value
}

func (v *NullableWebhookEndpoint) Set(val *WebhookEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpoint(val *WebhookEndpoint) *NullableWebhookEndpoint {
	return &NullableWebhookEndpoint{value: val, isSet: true}
}

func (v NullableWebhookEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


