/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookEndpointCreated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpointCreated{}

// WebhookEndpointCreated struct for WebhookEndpointCreated
type WebhookEndpointCreated struct {
	Id string `json:"id"`
	Url string `json:"url"`
	Events []WebhookEventType `json:"events"`
	Active bool `json:"active"`
	// The `whsec_` HMAC signing secret. Shown ONCE, at create, never again.
	Secret string `json:"secret"`
}

type _WebhookEndpointCreated WebhookEndpointCreated

// NewWebhookEndpointCreated instantiates a new WebhookEndpointCreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointCreated(id string, url string, events []WebhookEventType, active bool, secret string) *WebhookEndpointCreated {
	this := WebhookEndpointCreated{}
	this.Id = id
	this.Url = url
	this.Events = events
	this.Active = active
	this.Secret = secret
	return &this
}

// NewWebhookEndpointCreatedWithDefaults instantiates a new WebhookEndpointCreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointCreatedWithDefaults() *WebhookEndpointCreated {
	this := WebhookEndpointCreated{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookEndpointCreated) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreated) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookEndpointCreated) SetId(v string) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *WebhookEndpointCreated) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreated) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookEndpointCreated) SetUrl(v string) {
	o.Url = v
}

// GetEvents returns the Events field value
func (o *WebhookEndpointCreated) GetEvents() []WebhookEventType {
	if o == nil {
		var ret []WebhookEventType
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreated) GetEventsOk() ([]WebhookEventType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookEndpointCreated) SetEvents(v []WebhookEventType) {
	o.Events = v
}

// GetActive returns the Active field value
func (o *WebhookEndpointCreated) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreated) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *WebhookEndpointCreated) SetActive(v bool) {
	o.Active = v
}

// GetSecret returns the Secret field value
func (o *WebhookEndpointCreated) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointCreated) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *WebhookEndpointCreated) SetSecret(v string) {
	o.Secret = v
}

func (o WebhookEndpointCreated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpointCreated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	toSerialize["events"] = o.Events
	toSerialize["active"] = o.Active
	toSerialize["secret"] = o.Secret
	return toSerialize, nil
}

func (o *WebhookEndpointCreated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"events",
		"active",
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEndpointCreated := _WebhookEndpointCreated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEndpointCreated)

	if err != nil {
		return err
	}

	*o = WebhookEndpointCreated(varWebhookEndpointCreated)

	return err
}

type NullableWebhookEndpointCreated struct {
	value *WebhookEndpointCreated
	isSet bool
}

func (v NullableWebhookEndpointCreated) Get() *WebhookEndpointCreated {
	return v.value
}

func (v *NullableWebhookEndpointCreated) Set(val *WebhookEndpointCreated) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointCreated) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointCreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointCreated(val *WebhookEndpointCreated) *NullableWebhookEndpointCreated {
	return &NullableWebhookEndpointCreated{value: val, isSet: true}
}

func (v NullableWebhookEndpointCreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointCreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


