/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RememberRequestEdgesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RememberRequestEdgesInner{}

// RememberRequestEdgesInner struct for RememberRequestEdgesInner
type RememberRequestEdgesInner struct {
	Relation string `json:"relation"`
	To string `json:"to"`
}

type _RememberRequestEdgesInner RememberRequestEdgesInner

// NewRememberRequestEdgesInner instantiates a new RememberRequestEdgesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRememberRequestEdgesInner(relation string, to string) *RememberRequestEdgesInner {
	this := RememberRequestEdgesInner{}
	this.Relation = relation
	this.To = to
	return &this
}

// NewRememberRequestEdgesInnerWithDefaults instantiates a new RememberRequestEdgesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRememberRequestEdgesInnerWithDefaults() *RememberRequestEdgesInner {
	this := RememberRequestEdgesInner{}
	return &this
}

// GetRelation returns the Relation field value
func (o *RememberRequestEdgesInner) GetRelation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Relation
}

// GetRelationOk returns a tuple with the Relation field value
// and a boolean to check if the value has been set.
func (o *RememberRequestEdgesInner) GetRelationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relation, true
}

// SetRelation sets field value
func (o *RememberRequestEdgesInner) SetRelation(v string) {
	o.Relation = v
}

// GetTo returns the To field value
func (o *RememberRequestEdgesInner) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *RememberRequestEdgesInner) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *RememberRequestEdgesInner) SetTo(v string) {
	o.To = v
}

func (o RememberRequestEdgesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RememberRequestEdgesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["relation"] = o.Relation
	toSerialize["to"] = o.To
	return toSerialize, nil
}

func (o *RememberRequestEdgesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"relation",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRememberRequestEdgesInner := _RememberRequestEdgesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRememberRequestEdgesInner)

	if err != nil {
		return err
	}

	*o = RememberRequestEdgesInner(varRememberRequestEdgesInner)

	return err
}

type NullableRememberRequestEdgesInner struct {
	value *RememberRequestEdgesInner
	isSet bool
}

func (v NullableRememberRequestEdgesInner) Get() *RememberRequestEdgesInner {
	return v.value
}

func (v *NullableRememberRequestEdgesInner) Set(val *RememberRequestEdgesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRememberRequestEdgesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRememberRequestEdgesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRememberRequestEdgesInner(val *RememberRequestEdgesInner) *NullableRememberRequestEdgesInner {
	return &NullableRememberRequestEdgesInner{value: val, isSet: true}
}

func (v NullableRememberRequestEdgesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRememberRequestEdgesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


