/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Cart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cart{}

// Cart A server-authoritative priced checkout state. Beta.
type Cart struct {
	Id string `json:"id"`
	Total Amount `json:"total"`
	LineItems []map[string]interface{} `json:"line_items,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Cart Cart

// NewCart instantiates a new Cart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCart(id string, total Amount) *Cart {
	this := Cart{}
	this.Id = id
	this.Total = total
	return &this
}

// NewCartWithDefaults instantiates a new Cart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartWithDefaults() *Cart {
	this := Cart{}
	return &this
}

// GetId returns the Id field value
func (o *Cart) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Cart) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Cart) SetId(v string) {
	o.Id = v
}

// GetTotal returns the Total field value
func (o *Cart) GetTotal() Amount {
	if o == nil {
		var ret Amount
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *Cart) GetTotalOk() (*Amount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *Cart) SetTotal(v Amount) {
	o.Total = v
}

// GetLineItems returns the LineItems field value if set, zero value otherwise.
func (o *Cart) GetLineItems() []map[string]interface{} {
	if o == nil || IsNil(o.LineItems) {
		var ret []map[string]interface{}
		return ret
	}
	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cart) GetLineItemsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *Cart) HasLineItems() bool {
	if o != nil && !IsNil(o.LineItems) {
		return true
	}

	return false
}

// SetLineItems gets a reference to the given []map[string]interface{} and assigns it to the LineItems field.
func (o *Cart) SetLineItems(v []map[string]interface{}) {
	o.LineItems = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *Cart) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cart) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *Cart) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *Cart) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o Cart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["total"] = o.Total
	if !IsNil(o.LineItems) {
		toSerialize["line_items"] = o.LineItems
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Cart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCart := _Cart{}

	err = json.Unmarshal(data, &varCart)

	if err != nil {
		return err
	}

	*o = Cart(varCart)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "total")
		delete(additionalProperties, "line_items")
		delete(additionalProperties, "expires_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCart struct {
	value *Cart
	isSet bool
}

func (v NullableCart) Get() *Cart {
	return v.value
}

func (v *NullableCart) Set(val *Cart) {
	v.value = val
	v.isSet = true
}

func (v NullableCart) IsSet() bool {
	return v.isSet
}

func (v *NullableCart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCart(val *Cart) *NullableCart {
	return &NullableCart{value: val, isSet: true}
}

func (v NullableCart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


