/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperatorRationale type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRationale{}

// OperatorRationale struct for OperatorRationale
type OperatorRationale struct {
	Rationale string `json:"rationale"`
}

type _OperatorRationale OperatorRationale

// NewOperatorRationale instantiates a new OperatorRationale object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRationale(rationale string) *OperatorRationale {
	this := OperatorRationale{}
	this.Rationale = rationale
	return &this
}

// NewOperatorRationaleWithDefaults instantiates a new OperatorRationale object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRationaleWithDefaults() *OperatorRationale {
	this := OperatorRationale{}
	return &this
}

// GetRationale returns the Rationale field value
func (o *OperatorRationale) GetRationale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rationale
}

// GetRationaleOk returns a tuple with the Rationale field value
// and a boolean to check if the value has been set.
func (o *OperatorRationale) GetRationaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rationale, true
}

// SetRationale sets field value
func (o *OperatorRationale) SetRationale(v string) {
	o.Rationale = v
}

func (o OperatorRationale) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRationale) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rationale"] = o.Rationale
	return toSerialize, nil
}

func (o *OperatorRationale) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rationale",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorRationale := _OperatorRationale{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorRationale)

	if err != nil {
		return err
	}

	*o = OperatorRationale(varOperatorRationale)

	return err
}

type NullableOperatorRationale struct {
	value *OperatorRationale
	isSet bool
}

func (v NullableOperatorRationale) Get() *OperatorRationale {
	return v.value
}

func (v *NullableOperatorRationale) Set(val *OperatorRationale) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRationale) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRationale) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRationale(val *OperatorRationale) *NullableOperatorRationale {
	return &NullableOperatorRationale{value: val, isSet: true}
}

func (v NullableOperatorRationale) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRationale) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


