/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MemoryMandate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryMandate{}

// MemoryMandate Scopes an agent's memory authority — the memory analog of the spend mandate. `asOfFloor` bounds how far back a recall may reach (a recall `validAt` earlier than it is refused). 
type MemoryMandate struct {
	Namespace string `json:"namespace"`
	CanRead bool `json:"canRead"`
	CanWrite bool `json:"canWrite"`
	CanErase bool `json:"canErase"`
	AsOfFloor *time.Time `json:"asOfFloor,omitempty"`
}

type _MemoryMandate MemoryMandate

// NewMemoryMandate instantiates a new MemoryMandate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryMandate(namespace string, canRead bool, canWrite bool, canErase bool) *MemoryMandate {
	this := MemoryMandate{}
	this.Namespace = namespace
	this.CanRead = canRead
	this.CanWrite = canWrite
	this.CanErase = canErase
	return &this
}

// NewMemoryMandateWithDefaults instantiates a new MemoryMandate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryMandateWithDefaults() *MemoryMandate {
	this := MemoryMandate{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *MemoryMandate) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *MemoryMandate) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *MemoryMandate) SetNamespace(v string) {
	o.Namespace = v
}

// GetCanRead returns the CanRead field value
func (o *MemoryMandate) GetCanRead() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanRead
}

// GetCanReadOk returns a tuple with the CanRead field value
// and a boolean to check if the value has been set.
func (o *MemoryMandate) GetCanReadOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanRead, true
}

// SetCanRead sets field value
func (o *MemoryMandate) SetCanRead(v bool) {
	o.CanRead = v
}

// GetCanWrite returns the CanWrite field value
func (o *MemoryMandate) GetCanWrite() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanWrite
}

// GetCanWriteOk returns a tuple with the CanWrite field value
// and a boolean to check if the value has been set.
func (o *MemoryMandate) GetCanWriteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanWrite, true
}

// SetCanWrite sets field value
func (o *MemoryMandate) SetCanWrite(v bool) {
	o.CanWrite = v
}

// GetCanErase returns the CanErase field value
func (o *MemoryMandate) GetCanErase() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanErase
}

// GetCanEraseOk returns a tuple with the CanErase field value
// and a boolean to check if the value has been set.
func (o *MemoryMandate) GetCanEraseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanErase, true
}

// SetCanErase sets field value
func (o *MemoryMandate) SetCanErase(v bool) {
	o.CanErase = v
}

// GetAsOfFloor returns the AsOfFloor field value if set, zero value otherwise.
func (o *MemoryMandate) GetAsOfFloor() time.Time {
	if o == nil || IsNil(o.AsOfFloor) {
		var ret time.Time
		return ret
	}
	return *o.AsOfFloor
}

// GetAsOfFloorOk returns a tuple with the AsOfFloor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryMandate) GetAsOfFloorOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AsOfFloor) {
		return nil, false
	}
	return o.AsOfFloor, true
}

// HasAsOfFloor returns a boolean if a field has been set.
func (o *MemoryMandate) HasAsOfFloor() bool {
	if o != nil && !IsNil(o.AsOfFloor) {
		return true
	}

	return false
}

// SetAsOfFloor gets a reference to the given time.Time and assigns it to the AsOfFloor field.
func (o *MemoryMandate) SetAsOfFloor(v time.Time) {
	o.AsOfFloor = &v
}

func (o MemoryMandate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryMandate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["namespace"] = o.Namespace
	toSerialize["canRead"] = o.CanRead
	toSerialize["canWrite"] = o.CanWrite
	toSerialize["canErase"] = o.CanErase
	if !IsNil(o.AsOfFloor) {
		toSerialize["asOfFloor"] = o.AsOfFloor
	}
	return toSerialize, nil
}

func (o *MemoryMandate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"canRead",
		"canWrite",
		"canErase",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryMandate := _MemoryMandate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemoryMandate)

	if err != nil {
		return err
	}

	*o = MemoryMandate(varMemoryMandate)

	return err
}

type NullableMemoryMandate struct {
	value *MemoryMandate
	isSet bool
}

func (v NullableMemoryMandate) Get() *MemoryMandate {
	return v.value
}

func (v *NullableMemoryMandate) Set(val *MemoryMandate) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryMandate) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryMandate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryMandate(val *MemoryMandate) *NullableMemoryMandate {
	return &NullableMemoryMandate{value: val, isSet: true}
}

func (v NullableMemoryMandate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryMandate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


