/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperatorRefund type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorRefund{}

// OperatorRefund struct for OperatorRefund
type OperatorRefund struct {
	IntentId string `json:"intent_id"`
	// Minor units to refund. Omitted, the full outstanding amount.
	AmountMinor *int32 `json:"amount_minor,omitempty"`
	Rationale string `json:"rationale"`
}

type _OperatorRefund OperatorRefund

// NewOperatorRefund instantiates a new OperatorRefund object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorRefund(intentId string, rationale string) *OperatorRefund {
	this := OperatorRefund{}
	this.IntentId = intentId
	this.Rationale = rationale
	return &this
}

// NewOperatorRefundWithDefaults instantiates a new OperatorRefund object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorRefundWithDefaults() *OperatorRefund {
	this := OperatorRefund{}
	return &this
}

// GetIntentId returns the IntentId field value
func (o *OperatorRefund) GetIntentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntentId
}

// GetIntentIdOk returns a tuple with the IntentId field value
// and a boolean to check if the value has been set.
func (o *OperatorRefund) GetIntentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntentId, true
}

// SetIntentId sets field value
func (o *OperatorRefund) SetIntentId(v string) {
	o.IntentId = v
}

// GetAmountMinor returns the AmountMinor field value if set, zero value otherwise.
func (o *OperatorRefund) GetAmountMinor() int32 {
	if o == nil || IsNil(o.AmountMinor) {
		var ret int32
		return ret
	}
	return *o.AmountMinor
}

// GetAmountMinorOk returns a tuple with the AmountMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorRefund) GetAmountMinorOk() (*int32, bool) {
	if o == nil || IsNil(o.AmountMinor) {
		return nil, false
	}
	return o.AmountMinor, true
}

// HasAmountMinor returns a boolean if a field has been set.
func (o *OperatorRefund) HasAmountMinor() bool {
	if o != nil && !IsNil(o.AmountMinor) {
		return true
	}

	return false
}

// SetAmountMinor gets a reference to the given int32 and assigns it to the AmountMinor field.
func (o *OperatorRefund) SetAmountMinor(v int32) {
	o.AmountMinor = &v
}

// GetRationale returns the Rationale field value
func (o *OperatorRefund) GetRationale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rationale
}

// GetRationaleOk returns a tuple with the Rationale field value
// and a boolean to check if the value has been set.
func (o *OperatorRefund) GetRationaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rationale, true
}

// SetRationale sets field value
func (o *OperatorRefund) SetRationale(v string) {
	o.Rationale = v
}

func (o OperatorRefund) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorRefund) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["intent_id"] = o.IntentId
	if !IsNil(o.AmountMinor) {
		toSerialize["amount_minor"] = o.AmountMinor
	}
	toSerialize["rationale"] = o.Rationale
	return toSerialize, nil
}

func (o *OperatorRefund) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"intent_id",
		"rationale",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorRefund := _OperatorRefund{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorRefund)

	if err != nil {
		return err
	}

	*o = OperatorRefund(varOperatorRefund)

	return err
}

type NullableOperatorRefund struct {
	value *OperatorRefund
	isSet bool
}

func (v NullableOperatorRefund) Get() *OperatorRefund {
	return v.value
}

func (v *NullableOperatorRefund) Set(val *OperatorRefund) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorRefund) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorRefund) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorRefund(val *OperatorRefund) *NullableOperatorRefund {
	return &NullableOperatorRefund{value: val, isSet: true}
}

func (v NullableOperatorRefund) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorRefund) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


