/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// checks if the ResolveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveRequest{}

// ResolveRequest struct for ResolveRequest
type ResolveRequest struct {
	// A2A card URL, signed disclosure id, or CAIP-10 account.
	Ref string `json:"ref"`
	AdditionalProperties map[string]interface{}
}

type _ResolveRequest ResolveRequest

// NewResolveRequest instantiates a new ResolveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveRequest(ref string) *ResolveRequest {
	this := ResolveRequest{}
	this.Ref = ref
	return &this
}

// NewResolveRequestWithDefaults instantiates a new ResolveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveRequestWithDefaults() *ResolveRequest {
	this := ResolveRequest{}
	return &this
}

// GetRef returns the Ref field value
func (o *ResolveRequest) GetRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ref
}

// GetRefOk returns a tuple with the Ref field value
// and a boolean to check if the value has been set.
func (o *ResolveRequest) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ref, true
}

// SetRef sets field value
func (o *ResolveRequest) SetRef(v string) {
	o.Ref = v
}

func (o ResolveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ref"] = o.Ref

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResolveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ref",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolveRequest := _ResolveRequest{}

	err = json.Unmarshal(data, &varResolveRequest)

	if err != nil {
		return err
	}

	*o = ResolveRequest(varResolveRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ref")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResolveRequest struct {
	value *ResolveRequest
	isSet bool
}

func (v NullableResolveRequest) Get() *ResolveRequest {
	return v.value
}

func (v *NullableResolveRequest) Set(val *ResolveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveRequest(val *ResolveRequest) *NullableResolveRequest {
	return &NullableResolveRequest{value: val, isSet: true}
}

func (v NullableResolveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


