/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Decision type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Decision{}

// Decision The gate's decision on an Intent.
type Decision struct {
	Outcome Outcome `json:"outcome"`
	Reasons []string `json:"reasons"`
	MandateId string `json:"mandate_id"`
}

type _Decision Decision

// NewDecision instantiates a new Decision object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecision(outcome Outcome, reasons []string, mandateId string) *Decision {
	this := Decision{}
	this.Outcome = outcome
	this.Reasons = reasons
	this.MandateId = mandateId
	return &this
}

// NewDecisionWithDefaults instantiates a new Decision object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecisionWithDefaults() *Decision {
	this := Decision{}
	return &this
}

// GetOutcome returns the Outcome field value
func (o *Decision) GetOutcome() Outcome {
	if o == nil {
		var ret Outcome
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *Decision) GetOutcomeOk() (*Outcome, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *Decision) SetOutcome(v Outcome) {
	o.Outcome = v
}

// GetReasons returns the Reasons field value
func (o *Decision) GetReasons() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value
// and a boolean to check if the value has been set.
func (o *Decision) GetReasonsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reasons, true
}

// SetReasons sets field value
func (o *Decision) SetReasons(v []string) {
	o.Reasons = v
}

// GetMandateId returns the MandateId field value
func (o *Decision) GetMandateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MandateId
}

// GetMandateIdOk returns a tuple with the MandateId field value
// and a boolean to check if the value has been set.
func (o *Decision) GetMandateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MandateId, true
}

// SetMandateId sets field value
func (o *Decision) SetMandateId(v string) {
	o.MandateId = v
}

func (o Decision) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Decision) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["outcome"] = o.Outcome
	toSerialize["reasons"] = o.Reasons
	toSerialize["mandate_id"] = o.MandateId
	return toSerialize, nil
}

func (o *Decision) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"outcome",
		"reasons",
		"mandate_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDecision := _Decision{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDecision)

	if err != nil {
		return err
	}

	*o = Decision(varDecision)

	return err
}

type NullableDecision struct {
	value *Decision
	isSet bool
}

func (v NullableDecision) Get() *Decision {
	return v.value
}

func (v *NullableDecision) Set(val *Decision) {
	v.value = val
	v.isSet = true
}

func (v NullableDecision) IsSet() bool {
	return v.isSet
}

func (v *NullableDecision) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecision(val *Decision) *NullableDecision {
	return &NullableDecision{value: val, isSet: true}
}

func (v NullableDecision) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecision) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


