/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the RecallRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecallRequest{}

// RecallRequest A point-in-time read. The mandate needs `canRead`.
type RecallRequest struct {
	Mandate MemoryMandate `json:"mandate"`
	ValidAt time.Time `json:"validAt"`
	TxAt time.Time `json:"txAt"`
	Namespace *string `json:"namespace,omitempty"`
}

type _RecallRequest RecallRequest

// NewRecallRequest instantiates a new RecallRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecallRequest(mandate MemoryMandate, validAt time.Time, txAt time.Time) *RecallRequest {
	this := RecallRequest{}
	this.Mandate = mandate
	this.ValidAt = validAt
	this.TxAt = txAt
	return &this
}

// NewRecallRequestWithDefaults instantiates a new RecallRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecallRequestWithDefaults() *RecallRequest {
	this := RecallRequest{}
	return &this
}

// GetMandate returns the Mandate field value
func (o *RecallRequest) GetMandate() MemoryMandate {
	if o == nil {
		var ret MemoryMandate
		return ret
	}

	return o.Mandate
}

// GetMandateOk returns a tuple with the Mandate field value
// and a boolean to check if the value has been set.
func (o *RecallRequest) GetMandateOk() (*MemoryMandate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mandate, true
}

// SetMandate sets field value
func (o *RecallRequest) SetMandate(v MemoryMandate) {
	o.Mandate = v
}

// GetValidAt returns the ValidAt field value
func (o *RecallRequest) GetValidAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValidAt
}

// GetValidAtOk returns a tuple with the ValidAt field value
// and a boolean to check if the value has been set.
func (o *RecallRequest) GetValidAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidAt, true
}

// SetValidAt sets field value
func (o *RecallRequest) SetValidAt(v time.Time) {
	o.ValidAt = v
}

// GetTxAt returns the TxAt field value
func (o *RecallRequest) GetTxAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.TxAt
}

// GetTxAtOk returns a tuple with the TxAt field value
// and a boolean to check if the value has been set.
func (o *RecallRequest) GetTxAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxAt, true
}

// SetTxAt sets field value
func (o *RecallRequest) SetTxAt(v time.Time) {
	o.TxAt = v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *RecallRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *RecallRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *RecallRequest) SetNamespace(v string) {
	o.Namespace = &v
}

func (o RecallRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecallRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mandate"] = o.Mandate
	toSerialize["validAt"] = o.ValidAt
	toSerialize["txAt"] = o.TxAt
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	return toSerialize, nil
}

func (o *RecallRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mandate",
		"validAt",
		"txAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecallRequest := _RecallRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecallRequest)

	if err != nil {
		return err
	}

	*o = RecallRequest(varRecallRequest)

	return err
}

type NullableRecallRequest struct {
	value *RecallRequest
	isSet bool
}

func (v NullableRecallRequest) Get() *RecallRequest {
	return v.value
}

func (v *NullableRecallRequest) Set(val *RecallRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRecallRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRecallRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecallRequest(val *RecallRequest) *NullableRecallRequest {
	return &NullableRecallRequest{value: val, isSet: true}
}

func (v NullableRecallRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecallRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


