/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// checks if the Proof type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Proof{}

// Proof A falsifiable Proof-of-Enforcement record binding authorization scope to execution outcome.
type Proof struct {
	// Byte-identical between the enforcement emitter and the independent verifier.
	PolicyHash string `json:"policy_hash"`
	IntentKey string `json:"intent_key"`
	Verified *bool `json:"verified,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Proof Proof

// NewProof instantiates a new Proof object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProof(policyHash string, intentKey string) *Proof {
	this := Proof{}
	this.PolicyHash = policyHash
	this.IntentKey = intentKey
	return &this
}

// NewProofWithDefaults instantiates a new Proof object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProofWithDefaults() *Proof {
	this := Proof{}
	return &this
}

// GetPolicyHash returns the PolicyHash field value
func (o *Proof) GetPolicyHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyHash
}

// GetPolicyHashOk returns a tuple with the PolicyHash field value
// and a boolean to check if the value has been set.
func (o *Proof) GetPolicyHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyHash, true
}

// SetPolicyHash sets field value
func (o *Proof) SetPolicyHash(v string) {
	o.PolicyHash = v
}

// GetIntentKey returns the IntentKey field value
func (o *Proof) GetIntentKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntentKey
}

// GetIntentKeyOk returns a tuple with the IntentKey field value
// and a boolean to check if the value has been set.
func (o *Proof) GetIntentKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntentKey, true
}

// SetIntentKey sets field value
func (o *Proof) SetIntentKey(v string) {
	o.IntentKey = v
}

// GetVerified returns the Verified field value if set, zero value otherwise.
func (o *Proof) GetVerified() bool {
	if o == nil || IsNil(o.Verified) {
		var ret bool
		return ret
	}
	return *o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Proof) GetVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Verified) {
		return nil, false
	}
	return o.Verified, true
}

// HasVerified returns a boolean if a field has been set.
func (o *Proof) HasVerified() bool {
	if o != nil && !IsNil(o.Verified) {
		return true
	}

	return false
}

// SetVerified gets a reference to the given bool and assigns it to the Verified field.
func (o *Proof) SetVerified(v bool) {
	o.Verified = &v
}

func (o Proof) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Proof) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy_hash"] = o.PolicyHash
	toSerialize["intent_key"] = o.IntentKey
	if !IsNil(o.Verified) {
		toSerialize["verified"] = o.Verified
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Proof) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy_hash",
		"intent_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProof := _Proof{}

	err = json.Unmarshal(data, &varProof)

	if err != nil {
		return err
	}

	*o = Proof(varProof)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "policy_hash")
		delete(additionalProperties, "intent_key")
		delete(additionalProperties, "verified")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProof struct {
	value *Proof
	isSet bool
}

func (v NullableProof) Get() *Proof {
	return v.value
}

func (v *NullableProof) Set(val *Proof) {
	v.value = val
	v.isSet = true
}

func (v NullableProof) IsSet() bool {
	return v.isSet
}

func (v *NullableProof) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProof(val *Proof) *NullableProof {
	return &NullableProof{value: val, isSet: true}
}

func (v NullableProof) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProof) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


