/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Job type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Job{}

// Job A read projection over an intent's confirm-park-approve lifecycle.
type Job struct {
	// The idempotency/intent key — the stable resource id.
	Id string `json:"id"`
	Status JobStatus `json:"status"`
	// The intent's first audit entry, falling back to its settle time.
	CreatedAt time.Time `json:"created_at"`
	// Set ONLY for terminal states (settled/denied/failed).
	TerminalAt *time.Time `json:"terminal_at,omitempty"`
	Outcome Outcome `json:"outcome"`
	Receipt *Receipt `json:"receipt,omitempty"`
	Problem *Problem `json:"problem,omitempty"`
	Pending *JobPending `json:"pending,omitempty"`
	Links JobLinks `json:"links"`
	AdditionalProperties map[string]interface{}
}

type _Job Job

// NewJob instantiates a new Job object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJob(id string, status JobStatus, createdAt time.Time, outcome Outcome, links JobLinks) *Job {
	this := Job{}
	this.Id = id
	this.Status = status
	this.CreatedAt = createdAt
	this.Outcome = outcome
	this.Links = links
	return &this
}

// NewJobWithDefaults instantiates a new Job object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobWithDefaults() *Job {
	this := Job{}
	return &this
}

// GetId returns the Id field value
func (o *Job) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Job) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Job) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *Job) GetStatus() JobStatus {
	if o == nil {
		var ret JobStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Job) GetStatusOk() (*JobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Job) SetStatus(v JobStatus) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Job) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Job) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Job) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetTerminalAt returns the TerminalAt field value if set, zero value otherwise.
func (o *Job) GetTerminalAt() time.Time {
	if o == nil || IsNil(o.TerminalAt) {
		var ret time.Time
		return ret
	}
	return *o.TerminalAt
}

// GetTerminalAtOk returns a tuple with the TerminalAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetTerminalAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TerminalAt) {
		return nil, false
	}
	return o.TerminalAt, true
}

// HasTerminalAt returns a boolean if a field has been set.
func (o *Job) HasTerminalAt() bool {
	if o != nil && !IsNil(o.TerminalAt) {
		return true
	}

	return false
}

// SetTerminalAt gets a reference to the given time.Time and assigns it to the TerminalAt field.
func (o *Job) SetTerminalAt(v time.Time) {
	o.TerminalAt = &v
}

// GetOutcome returns the Outcome field value
func (o *Job) GetOutcome() Outcome {
	if o == nil {
		var ret Outcome
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *Job) GetOutcomeOk() (*Outcome, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *Job) SetOutcome(v Outcome) {
	o.Outcome = v
}

// GetReceipt returns the Receipt field value if set, zero value otherwise.
func (o *Job) GetReceipt() Receipt {
	if o == nil || IsNil(o.Receipt) {
		var ret Receipt
		return ret
	}
	return *o.Receipt
}

// GetReceiptOk returns a tuple with the Receipt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetReceiptOk() (*Receipt, bool) {
	if o == nil || IsNil(o.Receipt) {
		return nil, false
	}
	return o.Receipt, true
}

// HasReceipt returns a boolean if a field has been set.
func (o *Job) HasReceipt() bool {
	if o != nil && !IsNil(o.Receipt) {
		return true
	}

	return false
}

// SetReceipt gets a reference to the given Receipt and assigns it to the Receipt field.
func (o *Job) SetReceipt(v Receipt) {
	o.Receipt = &v
}

// GetProblem returns the Problem field value if set, zero value otherwise.
func (o *Job) GetProblem() Problem {
	if o == nil || IsNil(o.Problem) {
		var ret Problem
		return ret
	}
	return *o.Problem
}

// GetProblemOk returns a tuple with the Problem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetProblemOk() (*Problem, bool) {
	if o == nil || IsNil(o.Problem) {
		return nil, false
	}
	return o.Problem, true
}

// HasProblem returns a boolean if a field has been set.
func (o *Job) HasProblem() bool {
	if o != nil && !IsNil(o.Problem) {
		return true
	}

	return false
}

// SetProblem gets a reference to the given Problem and assigns it to the Problem field.
func (o *Job) SetProblem(v Problem) {
	o.Problem = &v
}

// GetPending returns the Pending field value if set, zero value otherwise.
func (o *Job) GetPending() JobPending {
	if o == nil || IsNil(o.Pending) {
		var ret JobPending
		return ret
	}
	return *o.Pending
}

// GetPendingOk returns a tuple with the Pending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Job) GetPendingOk() (*JobPending, bool) {
	if o == nil || IsNil(o.Pending) {
		return nil, false
	}
	return o.Pending, true
}

// HasPending returns a boolean if a field has been set.
func (o *Job) HasPending() bool {
	if o != nil && !IsNil(o.Pending) {
		return true
	}

	return false
}

// SetPending gets a reference to the given JobPending and assigns it to the Pending field.
func (o *Job) SetPending(v JobPending) {
	o.Pending = &v
}

// GetLinks returns the Links field value
func (o *Job) GetLinks() JobLinks {
	if o == nil {
		var ret JobLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *Job) GetLinksOk() (*JobLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *Job) SetLinks(v JobLinks) {
	o.Links = v
}

func (o Job) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Job) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.TerminalAt) {
		toSerialize["terminal_at"] = o.TerminalAt
	}
	toSerialize["outcome"] = o.Outcome
	if !IsNil(o.Receipt) {
		toSerialize["receipt"] = o.Receipt
	}
	if !IsNil(o.Problem) {
		toSerialize["problem"] = o.Problem
	}
	if !IsNil(o.Pending) {
		toSerialize["pending"] = o.Pending
	}
	toSerialize["links"] = o.Links

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Job) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"created_at",
		"outcome",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJob := _Job{}

	err = json.Unmarshal(data, &varJob)

	if err != nil {
		return err
	}

	*o = Job(varJob)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "terminal_at")
		delete(additionalProperties, "outcome")
		delete(additionalProperties, "receipt")
		delete(additionalProperties, "problem")
		delete(additionalProperties, "pending")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJob struct {
	value *Job
	isSet bool
}

func (v NullableJob) Get() *Job {
	return v.value
}

func (v *NullableJob) Set(val *Job) {
	v.value = val
	v.isSet = true
}

func (v NullableJob) IsSet() bool {
	return v.isSet
}

func (v *NullableJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJob(val *Job) *NullableJob {
	return &NullableJob{value: val, isSet: true}
}

func (v NullableJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


