/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssembledContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssembledContext{}

// AssembledContext A budgeted, ordered context assembled from a snapshot, under one seal. Abstention (`abstained: true`) is a valid result — the engine declining to fill the budget. 
type AssembledContext struct {
	Records []MemoryRecord `json:"records"`
	Order []string `json:"order"`
	Budget AssembledContextBudget `json:"budget"`
	Abstained bool `json:"abstained"`
	AbstainReason *string `json:"abstainReason,omitempty"`
	Seal Seal `json:"seal"`
}

type _AssembledContext AssembledContext

// NewAssembledContext instantiates a new AssembledContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssembledContext(records []MemoryRecord, order []string, budget AssembledContextBudget, abstained bool, seal Seal) *AssembledContext {
	this := AssembledContext{}
	this.Records = records
	this.Order = order
	this.Budget = budget
	this.Abstained = abstained
	this.Seal = seal
	return &this
}

// NewAssembledContextWithDefaults instantiates a new AssembledContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssembledContextWithDefaults() *AssembledContext {
	this := AssembledContext{}
	return &this
}

// GetRecords returns the Records field value
func (o *AssembledContext) GetRecords() []MemoryRecord {
	if o == nil {
		var ret []MemoryRecord
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *AssembledContext) GetRecordsOk() ([]MemoryRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *AssembledContext) SetRecords(v []MemoryRecord) {
	o.Records = v
}

// GetOrder returns the Order field value
func (o *AssembledContext) GetOrder() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *AssembledContext) GetOrderOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Order, true
}

// SetOrder sets field value
func (o *AssembledContext) SetOrder(v []string) {
	o.Order = v
}

// GetBudget returns the Budget field value
func (o *AssembledContext) GetBudget() AssembledContextBudget {
	if o == nil {
		var ret AssembledContextBudget
		return ret
	}

	return o.Budget
}

// GetBudgetOk returns a tuple with the Budget field value
// and a boolean to check if the value has been set.
func (o *AssembledContext) GetBudgetOk() (*AssembledContextBudget, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Budget, true
}

// SetBudget sets field value
func (o *AssembledContext) SetBudget(v AssembledContextBudget) {
	o.Budget = v
}

// GetAbstained returns the Abstained field value
func (o *AssembledContext) GetAbstained() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Abstained
}

// GetAbstainedOk returns a tuple with the Abstained field value
// and a boolean to check if the value has been set.
func (o *AssembledContext) GetAbstainedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Abstained, true
}

// SetAbstained sets field value
func (o *AssembledContext) SetAbstained(v bool) {
	o.Abstained = v
}

// GetAbstainReason returns the AbstainReason field value if set, zero value otherwise.
func (o *AssembledContext) GetAbstainReason() string {
	if o == nil || IsNil(o.AbstainReason) {
		var ret string
		return ret
	}
	return *o.AbstainReason
}

// GetAbstainReasonOk returns a tuple with the AbstainReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssembledContext) GetAbstainReasonOk() (*string, bool) {
	if o == nil || IsNil(o.AbstainReason) {
		return nil, false
	}
	return o.AbstainReason, true
}

// HasAbstainReason returns a boolean if a field has been set.
func (o *AssembledContext) HasAbstainReason() bool {
	if o != nil && !IsNil(o.AbstainReason) {
		return true
	}

	return false
}

// SetAbstainReason gets a reference to the given string and assigns it to the AbstainReason field.
func (o *AssembledContext) SetAbstainReason(v string) {
	o.AbstainReason = &v
}

// GetSeal returns the Seal field value
func (o *AssembledContext) GetSeal() Seal {
	if o == nil {
		var ret Seal
		return ret
	}

	return o.Seal
}

// GetSealOk returns a tuple with the Seal field value
// and a boolean to check if the value has been set.
func (o *AssembledContext) GetSealOk() (*Seal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seal, true
}

// SetSeal sets field value
func (o *AssembledContext) SetSeal(v Seal) {
	o.Seal = v
}

func (o AssembledContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssembledContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["records"] = o.Records
	toSerialize["order"] = o.Order
	toSerialize["budget"] = o.Budget
	toSerialize["abstained"] = o.Abstained
	if !IsNil(o.AbstainReason) {
		toSerialize["abstainReason"] = o.AbstainReason
	}
	toSerialize["seal"] = o.Seal
	return toSerialize, nil
}

func (o *AssembledContext) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
		"order",
		"budget",
		"abstained",
		"seal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssembledContext := _AssembledContext{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssembledContext)

	if err != nil {
		return err
	}

	*o = AssembledContext(varAssembledContext)

	return err
}

type NullableAssembledContext struct {
	value *AssembledContext
	isSet bool
}

func (v NullableAssembledContext) Get() *AssembledContext {
	return v.value
}

func (v *NullableAssembledContext) Set(val *AssembledContext) {
	v.value = val
	v.isSet = true
}

func (v NullableAssembledContext) IsSet() bool {
	return v.isSet
}

func (v *NullableAssembledContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssembledContext(val *AssembledContext) *NullableAssembledContext {
	return &NullableAssembledContext{value: val, isSet: true}
}

func (v NullableAssembledContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssembledContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


