/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Intent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Intent{}

// Intent A signed request to move value. Input to pay(); never carries a settle primitive.
type Intent struct {
	IdempotencyKey string `json:"idempotency_key"`
	// Resolved to a CAIP-10 account where the rail is on-chain.
	Payee string `json:"payee"`
	Amount Amount `json:"amount"`
	Purpose string `json:"purpose"`
	Terms Terms `json:"terms"`
	Envelope Envelope `json:"envelope"`
}

type _Intent Intent

// NewIntent instantiates a new Intent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntent(idempotencyKey string, payee string, amount Amount, purpose string, terms Terms, envelope Envelope) *Intent {
	this := Intent{}
	this.IdempotencyKey = idempotencyKey
	this.Payee = payee
	this.Amount = amount
	this.Purpose = purpose
	this.Terms = terms
	this.Envelope = envelope
	return &this
}

// NewIntentWithDefaults instantiates a new Intent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntentWithDefaults() *Intent {
	this := Intent{}
	return &this
}

// GetIdempotencyKey returns the IdempotencyKey field value
func (o *Intent) GetIdempotencyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value
// and a boolean to check if the value has been set.
func (o *Intent) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdempotencyKey, true
}

// SetIdempotencyKey sets field value
func (o *Intent) SetIdempotencyKey(v string) {
	o.IdempotencyKey = v
}

// GetPayee returns the Payee field value
func (o *Intent) GetPayee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Payee
}

// GetPayeeOk returns a tuple with the Payee field value
// and a boolean to check if the value has been set.
func (o *Intent) GetPayeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payee, true
}

// SetPayee sets field value
func (o *Intent) SetPayee(v string) {
	o.Payee = v
}

// GetAmount returns the Amount field value
func (o *Intent) GetAmount() Amount {
	if o == nil {
		var ret Amount
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *Intent) GetAmountOk() (*Amount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *Intent) SetAmount(v Amount) {
	o.Amount = v
}

// GetPurpose returns the Purpose field value
func (o *Intent) GetPurpose() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Purpose
}

// GetPurposeOk returns a tuple with the Purpose field value
// and a boolean to check if the value has been set.
func (o *Intent) GetPurposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Purpose, true
}

// SetPurpose sets field value
func (o *Intent) SetPurpose(v string) {
	o.Purpose = v
}

// GetTerms returns the Terms field value
func (o *Intent) GetTerms() Terms {
	if o == nil {
		var ret Terms
		return ret
	}

	return o.Terms
}

// GetTermsOk returns a tuple with the Terms field value
// and a boolean to check if the value has been set.
func (o *Intent) GetTermsOk() (*Terms, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Terms, true
}

// SetTerms sets field value
func (o *Intent) SetTerms(v Terms) {
	o.Terms = v
}

// GetEnvelope returns the Envelope field value
func (o *Intent) GetEnvelope() Envelope {
	if o == nil {
		var ret Envelope
		return ret
	}

	return o.Envelope
}

// GetEnvelopeOk returns a tuple with the Envelope field value
// and a boolean to check if the value has been set.
func (o *Intent) GetEnvelopeOk() (*Envelope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Envelope, true
}

// SetEnvelope sets field value
func (o *Intent) SetEnvelope(v Envelope) {
	o.Envelope = v
}

func (o Intent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Intent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["idempotency_key"] = o.IdempotencyKey
	toSerialize["payee"] = o.Payee
	toSerialize["amount"] = o.Amount
	toSerialize["purpose"] = o.Purpose
	toSerialize["terms"] = o.Terms
	toSerialize["envelope"] = o.Envelope
	return toSerialize, nil
}

func (o *Intent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"idempotency_key",
		"payee",
		"amount",
		"purpose",
		"terms",
		"envelope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntent := _Intent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntent)

	if err != nil {
		return err
	}

	*o = Intent(varIntent)

	return err
}

type NullableIntent struct {
	value *Intent
	isSet bool
}

func (v NullableIntent) Get() *Intent {
	return v.value
}

func (v *NullableIntent) Set(val *Intent) {
	v.value = val
	v.isSet = true
}

func (v NullableIntent) IsSet() bool {
	return v.isSet
}

func (v *NullableIntent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntent(val *Intent) *NullableIntent {
	return &NullableIntent{value: val, isSet: true}
}

func (v NullableIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


