/*
General Liquidity — The Machine Economy API

General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed `Intent`; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (`packages/sdk`) and the MCP server (`packages/mcp`) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per `docs/NAMING.md`: verbs are single common English words (`resolve`, `pay`, `verify`, `disclose`, `buy`, `quote`); nouns are concrete singular domain objects (`Intent`, `Mandate`, `Receipt`, `Counterparty`). The wire is `snake_case`; the TypeScript SDK presents `camelCase`. Vendor/protocol names appear only as lowercase `RailId` values, never as verbs or types. 

API version: 2026-07-22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// Finality the model 'Finality'
type Finality string

// List of Finality
const (
	INSTANT Finality = "instant"
	DEFERRED Finality = "deferred"
)

// All allowed values of Finality enum
var AllowedFinalityEnumValues = []Finality{
	"instant",
	"deferred",
}

func (v *Finality) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Finality(value)
	for _, existing := range AllowedFinalityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Finality", value)
}

// NewFinalityFromValue returns a pointer to a valid Finality
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFinalityFromValue(v string) (*Finality, error) {
	ev := Finality(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Finality: valid values are %v", v, AllowedFinalityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Finality) IsValid() bool {
	for _, existing := range AllowedFinalityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Finality value
func (v Finality) Ptr() *Finality {
	return &v
}

type NullableFinality struct {
	value *Finality
	isSet bool
}

func (v NullableFinality) Get() *Finality {
	return v.value
}

func (v *NullableFinality) Set(val *Finality) {
	v.value = val
	v.isSet = true
}

func (v NullableFinality) IsSet() bool {
	return v.isSet
}

func (v *NullableFinality) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinality(val *Finality) *NullableFinality {
	return &NullableFinality{value: val, isSet: true}
}

func (v NullableFinality) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinality) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

