/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PendingSettlement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PendingSettlement{}

// PendingSettlement An RFC 7807 problem (type `clearing.pending`) returned when an optional PENDING clearing band holds a bound spend: it was gated and authorized, but the obligation's admissibility floor is not yet met and the deadline has not passed, so the value is HELD rather than settled or refused. Retry once admissible evidence exists (the hold auto-releases to a `Receipt`); the hold refuses once the deadline passes. Only present on a stack that wired the clearing band's PENDING state. 
type PendingSettlement struct {
	Type string `json:"type"`
	Title string `json:"title"`
	// The obligation the spend is conditional on.
	ObligationId string `json:"obligation_id"`
	State string `json:"state"`
	// The admissibility class still awaited before the spend can settle.
	Awaiting EvidenceClass `json:"awaiting"`
	// The strongest class the admitted evidence has reached so far.
	AchievedClass *EvidenceClass `json:"achieved_class,omitempty"`
}

type _PendingSettlement PendingSettlement

// NewPendingSettlement instantiates a new PendingSettlement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPendingSettlement(type_ string, title string, obligationId string, state string, awaiting EvidenceClass) *PendingSettlement {
	this := PendingSettlement{}
	this.Type = type_
	this.Title = title
	this.ObligationId = obligationId
	this.State = state
	this.Awaiting = awaiting
	return &this
}

// NewPendingSettlementWithDefaults instantiates a new PendingSettlement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPendingSettlementWithDefaults() *PendingSettlement {
	this := PendingSettlement{}
	return &this
}

// GetType returns the Type field value
func (o *PendingSettlement) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PendingSettlement) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PendingSettlement) SetType(v string) {
	o.Type = v
}

// GetTitle returns the Title field value
func (o *PendingSettlement) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PendingSettlement) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PendingSettlement) SetTitle(v string) {
	o.Title = v
}

// GetObligationId returns the ObligationId field value
func (o *PendingSettlement) GetObligationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObligationId
}

// GetObligationIdOk returns a tuple with the ObligationId field value
// and a boolean to check if the value has been set.
func (o *PendingSettlement) GetObligationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObligationId, true
}

// SetObligationId sets field value
func (o *PendingSettlement) SetObligationId(v string) {
	o.ObligationId = v
}

// GetState returns the State field value
func (o *PendingSettlement) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *PendingSettlement) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *PendingSettlement) SetState(v string) {
	o.State = v
}

// GetAwaiting returns the Awaiting field value
func (o *PendingSettlement) GetAwaiting() EvidenceClass {
	if o == nil {
		var ret EvidenceClass
		return ret
	}

	return o.Awaiting
}

// GetAwaitingOk returns a tuple with the Awaiting field value
// and a boolean to check if the value has been set.
func (o *PendingSettlement) GetAwaitingOk() (*EvidenceClass, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Awaiting, true
}

// SetAwaiting sets field value
func (o *PendingSettlement) SetAwaiting(v EvidenceClass) {
	o.Awaiting = v
}

// GetAchievedClass returns the AchievedClass field value if set, zero value otherwise.
func (o *PendingSettlement) GetAchievedClass() EvidenceClass {
	if o == nil || IsNil(o.AchievedClass) {
		var ret EvidenceClass
		return ret
	}
	return *o.AchievedClass
}

// GetAchievedClassOk returns a tuple with the AchievedClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PendingSettlement) GetAchievedClassOk() (*EvidenceClass, bool) {
	if o == nil || IsNil(o.AchievedClass) {
		return nil, false
	}
	return o.AchievedClass, true
}

// HasAchievedClass returns a boolean if a field has been set.
func (o *PendingSettlement) HasAchievedClass() bool {
	if o != nil && !IsNil(o.AchievedClass) {
		return true
	}

	return false
}

// SetAchievedClass gets a reference to the given EvidenceClass and assigns it to the AchievedClass field.
func (o *PendingSettlement) SetAchievedClass(v EvidenceClass) {
	o.AchievedClass = &v
}

func (o PendingSettlement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PendingSettlement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["title"] = o.Title
	toSerialize["obligation_id"] = o.ObligationId
	toSerialize["state"] = o.State
	toSerialize["awaiting"] = o.Awaiting
	if !IsNil(o.AchievedClass) {
		toSerialize["achieved_class"] = o.AchievedClass
	}
	return toSerialize, nil
}

func (o *PendingSettlement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"title",
		"obligation_id",
		"state",
		"awaiting",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPendingSettlement := _PendingSettlement{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPendingSettlement)

	if err != nil {
		return err
	}

	*o = PendingSettlement(varPendingSettlement)

	return err
}

type NullablePendingSettlement struct {
	value *PendingSettlement
	isSet bool
}

func (v NullablePendingSettlement) Get() *PendingSettlement {
	return v.value
}

func (v *NullablePendingSettlement) Set(val *PendingSettlement) {
	v.value = val
	v.isSet = true
}

func (v NullablePendingSettlement) IsSet() bool {
	return v.isSet
}

func (v *NullablePendingSettlement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePendingSettlement(val *PendingSettlement) *NullablePendingSettlement {
	return &NullablePendingSettlement{value: val, isSet: true}
}

func (v NullablePendingSettlement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePendingSettlement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


