/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
)

// checks if the JobPending type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobPending{}

// JobPending Resume material, present only on a pending job.
type JobPending struct {
	MandateId *string `json:"mandateId,omitempty"`
	// Opaque challenge an operator approval binds to.
	Challenge *string `json:"challenge,omitempty"`
}

// NewJobPending instantiates a new JobPending object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobPending() *JobPending {
	this := JobPending{}
	return &this
}

// NewJobPendingWithDefaults instantiates a new JobPending object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobPendingWithDefaults() *JobPending {
	this := JobPending{}
	return &this
}

// GetMandateId returns the MandateId field value if set, zero value otherwise.
func (o *JobPending) GetMandateId() string {
	if o == nil || IsNil(o.MandateId) {
		var ret string
		return ret
	}
	return *o.MandateId
}

// GetMandateIdOk returns a tuple with the MandateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobPending) GetMandateIdOk() (*string, bool) {
	if o == nil || IsNil(o.MandateId) {
		return nil, false
	}
	return o.MandateId, true
}

// HasMandateId returns a boolean if a field has been set.
func (o *JobPending) HasMandateId() bool {
	if o != nil && !IsNil(o.MandateId) {
		return true
	}

	return false
}

// SetMandateId gets a reference to the given string and assigns it to the MandateId field.
func (o *JobPending) SetMandateId(v string) {
	o.MandateId = &v
}

// GetChallenge returns the Challenge field value if set, zero value otherwise.
func (o *JobPending) GetChallenge() string {
	if o == nil || IsNil(o.Challenge) {
		var ret string
		return ret
	}
	return *o.Challenge
}

// GetChallengeOk returns a tuple with the Challenge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobPending) GetChallengeOk() (*string, bool) {
	if o == nil || IsNil(o.Challenge) {
		return nil, false
	}
	return o.Challenge, true
}

// HasChallenge returns a boolean if a field has been set.
func (o *JobPending) HasChallenge() bool {
	if o != nil && !IsNil(o.Challenge) {
		return true
	}

	return false
}

// SetChallenge gets a reference to the given string and assigns it to the Challenge field.
func (o *JobPending) SetChallenge(v string) {
	o.Challenge = &v
}

func (o JobPending) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobPending) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MandateId) {
		toSerialize["mandateId"] = o.MandateId
	}
	if !IsNil(o.Challenge) {
		toSerialize["challenge"] = o.Challenge
	}
	return toSerialize, nil
}

type NullableJobPending struct {
	value *JobPending
	isSet bool
}

func (v NullableJobPending) Get() *JobPending {
	return v.value
}

func (v *NullableJobPending) Set(val *JobPending) {
	v.value = val
	v.isSet = true
}

func (v NullableJobPending) IsSet() bool {
	return v.isSet
}

func (v *NullableJobPending) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobPending(val *JobPending) *NullableJobPending {
	return &NullableJobPending{value: val, isSet: true}
}

func (v NullableJobPending) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobPending) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


