/*
General Liquidity — The Machine Economy API

General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed `Intent`; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (`packages/sdk`) and the MCP server (`packages/mcp`) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per `docs/NAMING.md`: verbs are single common English words (`resolve`, `pay`, `verify`, `disclose`, `buy`, `quote`); nouns are concrete singular domain objects (`Intent`, `Mandate`, `Receipt`, `Counterparty`). The wire is `snake_case`; the TypeScript SDK presents `camelCase`. Vendor/protocol names appear only as lowercase `RailId` values, never as verbs or types. 

API version: 2026-07-22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AuditEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditEvent{}

// AuditEvent A single signed, hash-linked entry in the audit trail.
type AuditEvent struct {
	// Monotonic wire event type, e.g. \"intent.gated\" | \"intent.settled\".
	Type string `json:"type"`
	At time.Time `json:"at"`
	IntentKey *string `json:"intent_key,omitempty"`
	// HMAC hash of the previous entry — the hash-link.
	Prev *string `json:"prev,omitempty"`
	Payload map[string]interface{} `json:"payload"`
	AdditionalProperties map[string]interface{}
}

type _AuditEvent AuditEvent

// NewAuditEvent instantiates a new AuditEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditEvent(type_ string, at time.Time, payload map[string]interface{}) *AuditEvent {
	this := AuditEvent{}
	this.Type = type_
	this.At = at
	this.Payload = payload
	return &this
}

// NewAuditEventWithDefaults instantiates a new AuditEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditEventWithDefaults() *AuditEvent {
	this := AuditEvent{}
	return &this
}

// GetType returns the Type field value
func (o *AuditEvent) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AuditEvent) SetType(v string) {
	o.Type = v
}

// GetAt returns the At field value
func (o *AuditEvent) GetAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.At
}

// GetAtOk returns a tuple with the At field value
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.At, true
}

// SetAt sets field value
func (o *AuditEvent) SetAt(v time.Time) {
	o.At = v
}

// GetIntentKey returns the IntentKey field value if set, zero value otherwise.
func (o *AuditEvent) GetIntentKey() string {
	if o == nil || IsNil(o.IntentKey) {
		var ret string
		return ret
	}
	return *o.IntentKey
}

// GetIntentKeyOk returns a tuple with the IntentKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetIntentKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IntentKey) {
		return nil, false
	}
	return o.IntentKey, true
}

// HasIntentKey returns a boolean if a field has been set.
func (o *AuditEvent) HasIntentKey() bool {
	if o != nil && !IsNil(o.IntentKey) {
		return true
	}

	return false
}

// SetIntentKey gets a reference to the given string and assigns it to the IntentKey field.
func (o *AuditEvent) SetIntentKey(v string) {
	o.IntentKey = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *AuditEvent) GetPrev() string {
	if o == nil || IsNil(o.Prev) {
		var ret string
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetPrevOk() (*string, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *AuditEvent) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given string and assigns it to the Prev field.
func (o *AuditEvent) SetPrev(v string) {
	o.Prev = &v
}

// GetPayload returns the Payload field value
func (o *AuditEvent) GetPayload() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// SetPayload sets field value
func (o *AuditEvent) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

func (o AuditEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["at"] = o.At
	if !IsNil(o.IntentKey) {
		toSerialize["intent_key"] = o.IntentKey
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}
	toSerialize["payload"] = o.Payload

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuditEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"at",
		"payload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditEvent := _AuditEvent{}

	err = json.Unmarshal(data, &varAuditEvent)

	if err != nil {
		return err
	}

	*o = AuditEvent(varAuditEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "at")
		delete(additionalProperties, "intent_key")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "payload")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuditEvent struct {
	value *AuditEvent
	isSet bool
}

func (v NullableAuditEvent) Get() *AuditEvent {
	return v.value
}

func (v *NullableAuditEvent) Set(val *AuditEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditEvent(val *AuditEvent) *NullableAuditEvent {
	return &NullableAuditEvent{value: val, isSet: true}
}

func (v NullableAuditEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


