/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Grant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Grant{}

// Grant An operator-counter-signed delegation of scope to an agent key.
type Grant struct {
	AgentId string `json:"agent_id"`
	MandateId string `json:"mandate_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Signature string `json:"signature"`
}

type _Grant Grant

// NewGrant instantiates a new Grant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrant(agentId string, mandateId string, expiresAt time.Time, signature string) *Grant {
	this := Grant{}
	this.AgentId = agentId
	this.MandateId = mandateId
	this.ExpiresAt = expiresAt
	this.Signature = signature
	return &this
}

// NewGrantWithDefaults instantiates a new Grant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantWithDefaults() *Grant {
	this := Grant{}
	return &this
}

// GetAgentId returns the AgentId field value
func (o *Grant) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *Grant) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *Grant) SetAgentId(v string) {
	o.AgentId = v
}

// GetMandateId returns the MandateId field value
func (o *Grant) GetMandateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MandateId
}

// GetMandateIdOk returns a tuple with the MandateId field value
// and a boolean to check if the value has been set.
func (o *Grant) GetMandateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MandateId, true
}

// SetMandateId sets field value
func (o *Grant) SetMandateId(v string) {
	o.MandateId = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *Grant) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *Grant) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *Grant) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetSignature returns the Signature field value
func (o *Grant) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *Grant) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *Grant) SetSignature(v string) {
	o.Signature = v
}

func (o Grant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Grant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_id"] = o.AgentId
	toSerialize["mandate_id"] = o.MandateId
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["signature"] = o.Signature
	return toSerialize, nil
}

func (o *Grant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_id",
		"mandate_id",
		"expires_at",
		"signature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGrant := _Grant{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGrant)

	if err != nil {
		return err
	}

	*o = Grant(varGrant)

	return err
}

type NullableGrant struct {
	value *Grant
	isSet bool
}

func (v NullableGrant) Get() *Grant {
	return v.value
}

func (v *NullableGrant) Set(val *Grant) {
	v.value = val
	v.isSet = true
}

func (v NullableGrant) IsSet() bool {
	return v.isSet
}

func (v *NullableGrant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrant(val *Grant) *NullableGrant {
	return &NullableGrant{value: val, isSet: true}
}

func (v NullableGrant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


