/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobLinks{}

// JobLinks struct for JobLinks
type JobLinks struct {
	Self string `json:"self"`
	Events string `json:"events"`
}

type _JobLinks JobLinks

// NewJobLinks instantiates a new JobLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobLinks(self string, events string) *JobLinks {
	this := JobLinks{}
	this.Self = self
	this.Events = events
	return &this
}

// NewJobLinksWithDefaults instantiates a new JobLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobLinksWithDefaults() *JobLinks {
	this := JobLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *JobLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *JobLinks) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *JobLinks) SetSelf(v string) {
	o.Self = v
}

// GetEvents returns the Events field value
func (o *JobLinks) GetEvents() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *JobLinks) GetEventsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Events, true
}

// SetEvents sets field value
func (o *JobLinks) SetEvents(v string) {
	o.Events = v
}

func (o JobLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *JobLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobLinks := _JobLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobLinks)

	if err != nil {
		return err
	}

	*o = JobLinks(varJobLinks)

	return err
}

type NullableJobLinks struct {
	value *JobLinks
	isSet bool
}

func (v NullableJobLinks) Get() *JobLinks {
	return v.value
}

func (v *NullableJobLinks) Set(val *JobLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableJobLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableJobLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobLinks(val *JobLinks) *NullableJobLinks {
	return &NullableJobLinks{value: val, isSet: true}
}

func (v NullableJobLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


