/*
General Liquidity — The Machine Economy API

General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed `Intent`; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (`packages/sdk`) and the MCP server (`packages/mcp`) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per `docs/NAMING.md`: verbs are single common English words (`resolve`, `pay`, `verify`, `disclose`, `buy`, `quote`); nouns are concrete singular domain objects (`Intent`, `Mandate`, `Receipt`, `Counterparty`). The wire is `snake_case`; the TypeScript SDK presents `camelCase`. Vendor/protocol names appear only as lowercase `RailId` values, never as verbs or types. 

API version: 2026-07-22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// Presence Human-presence requirement at authorization time.
type Presence string

// List of Presence
const (
	PRESENT Presence = "present"
	DELEGATED Presence = "delegated"
)

// All allowed values of Presence enum
var AllowedPresenceEnumValues = []Presence{
	"present",
	"delegated",
}

func (v *Presence) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Presence(value)
	for _, existing := range AllowedPresenceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Presence", value)
}

// NewPresenceFromValue returns a pointer to a valid Presence
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPresenceFromValue(v string) (*Presence, error) {
	ev := Presence(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Presence: valid values are %v", v, AllowedPresenceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Presence) IsValid() bool {
	for _, existing := range AllowedPresenceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Presence value
func (v Presence) Ptr() *Presence {
	return &v
}

type NullablePresence struct {
	value *Presence
	isSet bool
}

func (v NullablePresence) Get() *Presence {
	return v.value
}

func (v *NullablePresence) Set(val *Presence) {
	v.value = val
	v.isSet = true
}

func (v NullablePresence) IsSet() bool {
	return v.isSet
}

func (v *NullablePresence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePresence(val *Presence) *NullablePresence {
	return &NullablePresence{value: val, isSet: true}
}

func (v NullablePresence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePresence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

