/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperatorKillSwitch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorKillSwitch{}

// OperatorKillSwitch struct for OperatorKillSwitch
type OperatorKillSwitch struct {
	// True freezes the settle path; false releases it. Signed separately per direction.
	Engaged bool `json:"engaged"`
	Rationale string `json:"rationale"`
}

type _OperatorKillSwitch OperatorKillSwitch

// NewOperatorKillSwitch instantiates a new OperatorKillSwitch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorKillSwitch(engaged bool, rationale string) *OperatorKillSwitch {
	this := OperatorKillSwitch{}
	this.Engaged = engaged
	this.Rationale = rationale
	return &this
}

// NewOperatorKillSwitchWithDefaults instantiates a new OperatorKillSwitch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorKillSwitchWithDefaults() *OperatorKillSwitch {
	this := OperatorKillSwitch{}
	return &this
}

// GetEngaged returns the Engaged field value
func (o *OperatorKillSwitch) GetEngaged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Engaged
}

// GetEngagedOk returns a tuple with the Engaged field value
// and a boolean to check if the value has been set.
func (o *OperatorKillSwitch) GetEngagedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engaged, true
}

// SetEngaged sets field value
func (o *OperatorKillSwitch) SetEngaged(v bool) {
	o.Engaged = v
}

// GetRationale returns the Rationale field value
func (o *OperatorKillSwitch) GetRationale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rationale
}

// GetRationaleOk returns a tuple with the Rationale field value
// and a boolean to check if the value has been set.
func (o *OperatorKillSwitch) GetRationaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rationale, true
}

// SetRationale sets field value
func (o *OperatorKillSwitch) SetRationale(v string) {
	o.Rationale = v
}

func (o OperatorKillSwitch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorKillSwitch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["engaged"] = o.Engaged
	toSerialize["rationale"] = o.Rationale
	return toSerialize, nil
}

func (o *OperatorKillSwitch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"engaged",
		"rationale",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorKillSwitch := _OperatorKillSwitch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorKillSwitch)

	if err != nil {
		return err
	}

	*o = OperatorKillSwitch(varOperatorKillSwitch)

	return err
}

type NullableOperatorKillSwitch struct {
	value *OperatorKillSwitch
	isSet bool
}

func (v NullableOperatorKillSwitch) Get() *OperatorKillSwitch {
	return v.value
}

func (v *NullableOperatorKillSwitch) Set(val *OperatorKillSwitch) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorKillSwitch) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorKillSwitch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorKillSwitch(val *OperatorKillSwitch) *NullableOperatorKillSwitch {
	return &NullableOperatorKillSwitch{value: val, isSet: true}
}

func (v NullableOperatorKillSwitch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorKillSwitch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


