/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the KeyRotationStatement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyRotationStatement{}

// KeyRotationStatement One signed hop of a key-rotation chain: the old key signs the move to the new key, so an identity survives a key change (an agentId IS its public key). 
type KeyRotationStatement struct {
	Type string `json:"type"`
	// agentId (public key hex) being rotated away from.
	From string `json:"from"`
	// agentId (public key hex) being rotated to.
	To string `json:"to"`
	RotatedAt time.Time `json:"rotated_at"`
	// Old key's signature over {type, from, to, rotated_at} (hex).
	Signature string `json:"signature"`
}

type _KeyRotationStatement KeyRotationStatement

// NewKeyRotationStatement instantiates a new KeyRotationStatement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyRotationStatement(type_ string, from string, to string, rotatedAt time.Time, signature string) *KeyRotationStatement {
	this := KeyRotationStatement{}
	this.Type = type_
	this.From = from
	this.To = to
	this.RotatedAt = rotatedAt
	this.Signature = signature
	return &this
}

// NewKeyRotationStatementWithDefaults instantiates a new KeyRotationStatement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyRotationStatementWithDefaults() *KeyRotationStatement {
	this := KeyRotationStatement{}
	return &this
}

// GetType returns the Type field value
func (o *KeyRotationStatement) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *KeyRotationStatement) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *KeyRotationStatement) SetType(v string) {
	o.Type = v
}

// GetFrom returns the From field value
func (o *KeyRotationStatement) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *KeyRotationStatement) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *KeyRotationStatement) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *KeyRotationStatement) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *KeyRotationStatement) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *KeyRotationStatement) SetTo(v string) {
	o.To = v
}

// GetRotatedAt returns the RotatedAt field value
func (o *KeyRotationStatement) GetRotatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RotatedAt
}

// GetRotatedAtOk returns a tuple with the RotatedAt field value
// and a boolean to check if the value has been set.
func (o *KeyRotationStatement) GetRotatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotatedAt, true
}

// SetRotatedAt sets field value
func (o *KeyRotationStatement) SetRotatedAt(v time.Time) {
	o.RotatedAt = v
}

// GetSignature returns the Signature field value
func (o *KeyRotationStatement) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *KeyRotationStatement) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *KeyRotationStatement) SetSignature(v string) {
	o.Signature = v
}

func (o KeyRotationStatement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyRotationStatement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["rotated_at"] = o.RotatedAt
	toSerialize["signature"] = o.Signature
	return toSerialize, nil
}

func (o *KeyRotationStatement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"from",
		"to",
		"rotated_at",
		"signature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyRotationStatement := _KeyRotationStatement{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKeyRotationStatement)

	if err != nil {
		return err
	}

	*o = KeyRotationStatement(varKeyRotationStatement)

	return err
}

type NullableKeyRotationStatement struct {
	value *KeyRotationStatement
	isSet bool
}

func (v NullableKeyRotationStatement) Get() *KeyRotationStatement {
	return v.value
}

func (v *NullableKeyRotationStatement) Set(val *KeyRotationStatement) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyRotationStatement) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyRotationStatement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyRotationStatement(val *KeyRotationStatement) *NullableKeyRotationStatement {
	return &NullableKeyRotationStatement{value: val, isSet: true}
}

func (v NullableKeyRotationStatement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyRotationStatement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


