/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the MemoryRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryRecord{}

// MemoryRecord One bi-temporal memory record. `validFrom`/`validTo` are the VALID-time window (the world the fact is about); `recordedAt`/`invalidatedAt` are the TRANSACTION-time window (when the store learned it). No-lookahead: a snapshot at a past instant never reveals a later edit. 
type MemoryRecord struct {
	Id string `json:"id"`
	// The arbitrary record payload.
	Body interface{} `json:"body"`
	ValidFrom time.Time `json:"validFrom"`
	ValidTo time.Time `json:"validTo"`
	RecordedAt time.Time `json:"recordedAt"`
	InvalidatedAt time.Time `json:"invalidatedAt"`
	Edges []MemoryRecordEdgesInner `json:"edges"`
	Taint bool `json:"taint"`
	Source string `json:"source"`
	AdditionalProperties map[string]interface{}
}

type _MemoryRecord MemoryRecord

// NewMemoryRecord instantiates a new MemoryRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryRecord(id string, body interface{}, validFrom time.Time, validTo time.Time, recordedAt time.Time, invalidatedAt time.Time, edges []MemoryRecordEdgesInner, taint bool, source string) *MemoryRecord {
	this := MemoryRecord{}
	this.Id = id
	this.Body = body
	this.ValidFrom = validFrom
	this.ValidTo = validTo
	this.RecordedAt = recordedAt
	this.InvalidatedAt = invalidatedAt
	this.Edges = edges
	this.Taint = taint
	this.Source = source
	return &this
}

// NewMemoryRecordWithDefaults instantiates a new MemoryRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryRecordWithDefaults() *MemoryRecord {
	this := MemoryRecord{}
	return &this
}

// GetId returns the Id field value
func (o *MemoryRecord) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MemoryRecord) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MemoryRecord) SetId(v string) {
	o.Id = v
}

// GetBody returns the Body field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *MemoryRecord) GetBody() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryRecord) GetBodyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *MemoryRecord) SetBody(v interface{}) {
	o.Body = v
}

// GetValidFrom returns the ValidFrom field value
func (o *MemoryRecord) GetValidFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value
// and a boolean to check if the value has been set.
func (o *MemoryRecord) GetValidFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidFrom, true
}

// SetValidFrom sets field value
func (o *MemoryRecord) SetValidFrom(v time.Time) {
	o.ValidFrom = v
}

// GetValidTo returns the ValidTo field value
func (o *MemoryRecord) GetValidTo() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValidTo
}

// GetValidToOk returns a tuple with the ValidTo field value
// and a boolean to check if the value has been set.
func (o *MemoryRecord) GetValidToOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidTo, true
}

// SetValidTo sets field value
func (o *MemoryRecord) SetValidTo(v time.Time) {
	o.ValidTo = v
}

// GetRecordedAt returns the RecordedAt field value
func (o *MemoryRecord) GetRecordedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RecordedAt
}

// GetRecordedAtOk returns a tuple with the RecordedAt field value
// and a boolean to check if the value has been set.
func (o *MemoryRecord) GetRecordedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordedAt, true
}

// SetRecordedAt sets field value
func (o *MemoryRecord) SetRecordedAt(v time.Time) {
	o.RecordedAt = v
}

// GetInvalidatedAt returns the InvalidatedAt field value
func (o *MemoryRecord) GetInvalidatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.InvalidatedAt
}

// GetInvalidatedAtOk returns a tuple with the InvalidatedAt field value
// and a boolean to check if the value has been set.
func (o *MemoryRecord) GetInvalidatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvalidatedAt, true
}

// SetInvalidatedAt sets field value
func (o *MemoryRecord) SetInvalidatedAt(v time.Time) {
	o.InvalidatedAt = v
}

// GetEdges returns the Edges field value
func (o *MemoryRecord) GetEdges() []MemoryRecordEdgesInner {
	if o == nil {
		var ret []MemoryRecordEdgesInner
		return ret
	}

	return o.Edges
}

// GetEdgesOk returns a tuple with the Edges field value
// and a boolean to check if the value has been set.
func (o *MemoryRecord) GetEdgesOk() ([]MemoryRecordEdgesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Edges, true
}

// SetEdges sets field value
func (o *MemoryRecord) SetEdges(v []MemoryRecordEdgesInner) {
	o.Edges = v
}

// GetTaint returns the Taint field value
func (o *MemoryRecord) GetTaint() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Taint
}

// GetTaintOk returns a tuple with the Taint field value
// and a boolean to check if the value has been set.
func (o *MemoryRecord) GetTaintOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Taint, true
}

// SetTaint sets field value
func (o *MemoryRecord) SetTaint(v bool) {
	o.Taint = v
}

// GetSource returns the Source field value
func (o *MemoryRecord) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *MemoryRecord) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *MemoryRecord) SetSource(v string) {
	o.Source = v
}

func (o MemoryRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	toSerialize["validFrom"] = o.ValidFrom
	toSerialize["validTo"] = o.ValidTo
	toSerialize["recordedAt"] = o.RecordedAt
	toSerialize["invalidatedAt"] = o.InvalidatedAt
	toSerialize["edges"] = o.Edges
	toSerialize["taint"] = o.Taint
	toSerialize["source"] = o.Source

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MemoryRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"body",
		"validFrom",
		"validTo",
		"recordedAt",
		"invalidatedAt",
		"edges",
		"taint",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryRecord := _MemoryRecord{}

	err = json.Unmarshal(data, &varMemoryRecord)

	if err != nil {
		return err
	}

	*o = MemoryRecord(varMemoryRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "body")
		delete(additionalProperties, "validFrom")
		delete(additionalProperties, "validTo")
		delete(additionalProperties, "recordedAt")
		delete(additionalProperties, "invalidatedAt")
		delete(additionalProperties, "edges")
		delete(additionalProperties, "taint")
		delete(additionalProperties, "source")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMemoryRecord struct {
	value *MemoryRecord
	isSet bool
}

func (v NullableMemoryRecord) Get() *MemoryRecord {
	return v.value
}

func (v *NullableMemoryRecord) Set(val *MemoryRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryRecord(val *MemoryRecord) *NullableMemoryRecord {
	return &NullableMemoryRecord{value: val, isSet: true}
}

func (v NullableMemoryRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


