/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// checks if the Disclosure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Disclosure{}

// Disclosure A signed self-description (identity + provenance). GL's disclosure format. BREAKING CHANGE (version 2026-07-23): collapsed onto the full signed envelope. The prior shape {agent_id, document, signature: string} carried a single key and could not express key rotation; it is replaced by the structured ed25519 signature and an optional rotation_chain. The wire shape now equals the signed envelope both sides exchange, so a rotated signing key can disclose while the stable agent id (document.agentId) is preserved. No agent_id at the top level: it lives in the signed document. 
type Disclosure struct {
	// The signed disclosure document (an AgentDisclosure). Its `agentId` field is the stable identity the signature (and any rotation_chain) roots at. 
	Document map[string]interface{} `json:"document"`
	Signature DisclosureSignature `json:"signature"`
	// Present only when the signing key has rotated away from document.agentId; links the stable id to signature.public_key. Absent in the common no-rotation case. 
	RotationChain []KeyRotationStatement `json:"rotation_chain,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Disclosure Disclosure

// NewDisclosure instantiates a new Disclosure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisclosure(document map[string]interface{}, signature DisclosureSignature) *Disclosure {
	this := Disclosure{}
	this.Document = document
	this.Signature = signature
	return &this
}

// NewDisclosureWithDefaults instantiates a new Disclosure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisclosureWithDefaults() *Disclosure {
	this := Disclosure{}
	return &this
}

// GetDocument returns the Document field value
func (o *Disclosure) GetDocument() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Document
}

// GetDocumentOk returns a tuple with the Document field value
// and a boolean to check if the value has been set.
func (o *Disclosure) GetDocumentOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Document, true
}

// SetDocument sets field value
func (o *Disclosure) SetDocument(v map[string]interface{}) {
	o.Document = v
}

// GetSignature returns the Signature field value
func (o *Disclosure) GetSignature() DisclosureSignature {
	if o == nil {
		var ret DisclosureSignature
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *Disclosure) GetSignatureOk() (*DisclosureSignature, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *Disclosure) SetSignature(v DisclosureSignature) {
	o.Signature = v
}

// GetRotationChain returns the RotationChain field value if set, zero value otherwise.
func (o *Disclosure) GetRotationChain() []KeyRotationStatement {
	if o == nil || IsNil(o.RotationChain) {
		var ret []KeyRotationStatement
		return ret
	}
	return o.RotationChain
}

// GetRotationChainOk returns a tuple with the RotationChain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Disclosure) GetRotationChainOk() ([]KeyRotationStatement, bool) {
	if o == nil || IsNil(o.RotationChain) {
		return nil, false
	}
	return o.RotationChain, true
}

// HasRotationChain returns a boolean if a field has been set.
func (o *Disclosure) HasRotationChain() bool {
	if o != nil && !IsNil(o.RotationChain) {
		return true
	}

	return false
}

// SetRotationChain gets a reference to the given []KeyRotationStatement and assigns it to the RotationChain field.
func (o *Disclosure) SetRotationChain(v []KeyRotationStatement) {
	o.RotationChain = v
}

func (o Disclosure) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Disclosure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["document"] = o.Document
	toSerialize["signature"] = o.Signature
	if !IsNil(o.RotationChain) {
		toSerialize["rotation_chain"] = o.RotationChain
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Disclosure) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"document",
		"signature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisclosure := _Disclosure{}

	err = json.Unmarshal(data, &varDisclosure)

	if err != nil {
		return err
	}

	*o = Disclosure(varDisclosure)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "document")
		delete(additionalProperties, "signature")
		delete(additionalProperties, "rotation_chain")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDisclosure struct {
	value *Disclosure
	isSet bool
}

func (v NullableDisclosure) Get() *Disclosure {
	return v.value
}

func (v *NullableDisclosure) Set(val *Disclosure) {
	v.value = val
	v.isSet = true
}

func (v NullableDisclosure) IsSet() bool {
	return v.isSet
}

func (v *NullableDisclosure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisclosure(val *Disclosure) *NullableDisclosure {
	return &NullableDisclosure{value: val, isSet: true}
}

func (v NullableDisclosure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisclosure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


