/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ErasureProof type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErasureProof{}

// ErasureProof The signed cascading-erasure proof `forget` returns — the erased ids under a seal.
type ErasureProof struct {
	Erased []string `json:"erased"`
	Proof Seal `json:"proof"`
}

type _ErasureProof ErasureProof

// NewErasureProof instantiates a new ErasureProof object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErasureProof(erased []string, proof Seal) *ErasureProof {
	this := ErasureProof{}
	this.Erased = erased
	this.Proof = proof
	return &this
}

// NewErasureProofWithDefaults instantiates a new ErasureProof object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErasureProofWithDefaults() *ErasureProof {
	this := ErasureProof{}
	return &this
}

// GetErased returns the Erased field value
func (o *ErasureProof) GetErased() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Erased
}

// GetErasedOk returns a tuple with the Erased field value
// and a boolean to check if the value has been set.
func (o *ErasureProof) GetErasedOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Erased, true
}

// SetErased sets field value
func (o *ErasureProof) SetErased(v []string) {
	o.Erased = v
}

// GetProof returns the Proof field value
func (o *ErasureProof) GetProof() Seal {
	if o == nil {
		var ret Seal
		return ret
	}

	return o.Proof
}

// GetProofOk returns a tuple with the Proof field value
// and a boolean to check if the value has been set.
func (o *ErasureProof) GetProofOk() (*Seal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Proof, true
}

// SetProof sets field value
func (o *ErasureProof) SetProof(v Seal) {
	o.Proof = v
}

func (o ErasureProof) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErasureProof) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["erased"] = o.Erased
	toSerialize["proof"] = o.Proof
	return toSerialize, nil
}

func (o *ErasureProof) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"erased",
		"proof",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErasureProof := _ErasureProof{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErasureProof)

	if err != nil {
		return err
	}

	*o = ErasureProof(varErasureProof)

	return err
}

type NullableErasureProof struct {
	value *ErasureProof
	isSet bool
}

func (v NullableErasureProof) Get() *ErasureProof {
	return v.value
}

func (v *NullableErasureProof) Set(val *ErasureProof) {
	v.value = val
	v.isSet = true
}

func (v NullableErasureProof) IsSet() bool {
	return v.isSet
}

func (v *NullableErasureProof) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErasureProof(val *ErasureProof) *NullableErasureProof {
	return &NullableErasureProof{value: val, isSet: true}
}

func (v NullableErasureProof) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErasureProof) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


