/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssembleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssembleRequest{}

// AssembleRequest Budgeted context assembly over a supplied snapshot OR recall params.
type AssembleRequest struct {
	Mandate MemoryMandate `json:"mandate"`
	Snapshot *Snapshot `json:"snapshot,omitempty"`
	Recall *AssembleRequestRecall `json:"recall,omitempty"`
	Budget AssembledContextBudget `json:"budget"`
	Namespace *string `json:"namespace,omitempty"`
}

type _AssembleRequest AssembleRequest

// NewAssembleRequest instantiates a new AssembleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssembleRequest(mandate MemoryMandate, budget AssembledContextBudget) *AssembleRequest {
	this := AssembleRequest{}
	this.Mandate = mandate
	this.Budget = budget
	return &this
}

// NewAssembleRequestWithDefaults instantiates a new AssembleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssembleRequestWithDefaults() *AssembleRequest {
	this := AssembleRequest{}
	return &this
}

// GetMandate returns the Mandate field value
func (o *AssembleRequest) GetMandate() MemoryMandate {
	if o == nil {
		var ret MemoryMandate
		return ret
	}

	return o.Mandate
}

// GetMandateOk returns a tuple with the Mandate field value
// and a boolean to check if the value has been set.
func (o *AssembleRequest) GetMandateOk() (*MemoryMandate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mandate, true
}

// SetMandate sets field value
func (o *AssembleRequest) SetMandate(v MemoryMandate) {
	o.Mandate = v
}

// GetSnapshot returns the Snapshot field value if set, zero value otherwise.
func (o *AssembleRequest) GetSnapshot() Snapshot {
	if o == nil || IsNil(o.Snapshot) {
		var ret Snapshot
		return ret
	}
	return *o.Snapshot
}

// GetSnapshotOk returns a tuple with the Snapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssembleRequest) GetSnapshotOk() (*Snapshot, bool) {
	if o == nil || IsNil(o.Snapshot) {
		return nil, false
	}
	return o.Snapshot, true
}

// HasSnapshot returns a boolean if a field has been set.
func (o *AssembleRequest) HasSnapshot() bool {
	if o != nil && !IsNil(o.Snapshot) {
		return true
	}

	return false
}

// SetSnapshot gets a reference to the given Snapshot and assigns it to the Snapshot field.
func (o *AssembleRequest) SetSnapshot(v Snapshot) {
	o.Snapshot = &v
}

// GetRecall returns the Recall field value if set, zero value otherwise.
func (o *AssembleRequest) GetRecall() AssembleRequestRecall {
	if o == nil || IsNil(o.Recall) {
		var ret AssembleRequestRecall
		return ret
	}
	return *o.Recall
}

// GetRecallOk returns a tuple with the Recall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssembleRequest) GetRecallOk() (*AssembleRequestRecall, bool) {
	if o == nil || IsNil(o.Recall) {
		return nil, false
	}
	return o.Recall, true
}

// HasRecall returns a boolean if a field has been set.
func (o *AssembleRequest) HasRecall() bool {
	if o != nil && !IsNil(o.Recall) {
		return true
	}

	return false
}

// SetRecall gets a reference to the given AssembleRequestRecall and assigns it to the Recall field.
func (o *AssembleRequest) SetRecall(v AssembleRequestRecall) {
	o.Recall = &v
}

// GetBudget returns the Budget field value
func (o *AssembleRequest) GetBudget() AssembledContextBudget {
	if o == nil {
		var ret AssembledContextBudget
		return ret
	}

	return o.Budget
}

// GetBudgetOk returns a tuple with the Budget field value
// and a boolean to check if the value has been set.
func (o *AssembleRequest) GetBudgetOk() (*AssembledContextBudget, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Budget, true
}

// SetBudget sets field value
func (o *AssembleRequest) SetBudget(v AssembledContextBudget) {
	o.Budget = v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *AssembleRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssembleRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *AssembleRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *AssembleRequest) SetNamespace(v string) {
	o.Namespace = &v
}

func (o AssembleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssembleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mandate"] = o.Mandate
	if !IsNil(o.Snapshot) {
		toSerialize["snapshot"] = o.Snapshot
	}
	if !IsNil(o.Recall) {
		toSerialize["recall"] = o.Recall
	}
	toSerialize["budget"] = o.Budget
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	return toSerialize, nil
}

func (o *AssembleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mandate",
		"budget",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssembleRequest := _AssembleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssembleRequest)

	if err != nil {
		return err
	}

	*o = AssembleRequest(varAssembleRequest)

	return err
}

type NullableAssembleRequest struct {
	value *AssembleRequest
	isSet bool
}

func (v NullableAssembleRequest) Get() *AssembleRequest {
	return v.value
}

func (v *NullableAssembleRequest) Set(val *AssembleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssembleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssembleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssembleRequest(val *AssembleRequest) *NullableAssembleRequest {
	return &NullableAssembleRequest{value: val, isSet: true}
}

func (v NullableAssembleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssembleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


