/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemoryVerify200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryVerify200Response{}

// MemoryVerify200Response struct for MemoryVerify200Response
type MemoryVerify200Response struct {
	Valid bool `json:"valid"`
	Reason *string `json:"reason,omitempty"`
}

type _MemoryVerify200Response MemoryVerify200Response

// NewMemoryVerify200Response instantiates a new MemoryVerify200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryVerify200Response(valid bool) *MemoryVerify200Response {
	this := MemoryVerify200Response{}
	this.Valid = valid
	return &this
}

// NewMemoryVerify200ResponseWithDefaults instantiates a new MemoryVerify200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryVerify200ResponseWithDefaults() *MemoryVerify200Response {
	this := MemoryVerify200Response{}
	return &this
}

// GetValid returns the Valid field value
func (o *MemoryVerify200Response) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *MemoryVerify200Response) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *MemoryVerify200Response) SetValid(v bool) {
	o.Valid = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *MemoryVerify200Response) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryVerify200Response) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *MemoryVerify200Response) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *MemoryVerify200Response) SetReason(v string) {
	o.Reason = &v
}

func (o MemoryVerify200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryVerify200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["valid"] = o.Valid
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *MemoryVerify200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"valid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryVerify200Response := _MemoryVerify200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemoryVerify200Response)

	if err != nil {
		return err
	}

	*o = MemoryVerify200Response(varMemoryVerify200Response)

	return err
}

type NullableMemoryVerify200Response struct {
	value *MemoryVerify200Response
	isSet bool
}

func (v NullableMemoryVerify200Response) Get() *MemoryVerify200Response {
	return v.value
}

func (v *NullableMemoryVerify200Response) Set(val *MemoryVerify200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryVerify200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryVerify200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryVerify200Response(val *MemoryVerify200Response) *NullableMemoryVerify200Response {
	return &NullableMemoryVerify200Response{value: val, isSet: true}
}

func (v NullableMemoryVerify200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryVerify200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


