/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperatorApprove type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorApprove{}

// OperatorApprove Resume material for a parked intent, exactly as carried on an `approval.pending` problem, plus the operator's rationale and challenge-response acknowledgement. 
type OperatorApprove struct {
	// The parked intent id.
	IntentId string `json:"intent_id"`
	// The opaque challenge that binds this approval to that intent. Not a bearer credential.
	Challenge string `json:"challenge"`
	// The mandate the gate matched when it parked the intent.
	MandateId string `json:"mandate_id"`
	// Why the operator is releasing it. Recorded in the signed audit chain.
	Rationale string `json:"rationale"`
	// Explicit challenge-response acknowledgement. Never inferred: a high-risk, irreversible or large intent is not released unless this is `true`. 
	Acknowledged bool `json:"acknowledged"`
}

type _OperatorApprove OperatorApprove

// NewOperatorApprove instantiates a new OperatorApprove object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorApprove(intentId string, challenge string, mandateId string, rationale string, acknowledged bool) *OperatorApprove {
	this := OperatorApprove{}
	this.IntentId = intentId
	this.Challenge = challenge
	this.MandateId = mandateId
	this.Rationale = rationale
	this.Acknowledged = acknowledged
	return &this
}

// NewOperatorApproveWithDefaults instantiates a new OperatorApprove object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorApproveWithDefaults() *OperatorApprove {
	this := OperatorApprove{}
	return &this
}

// GetIntentId returns the IntentId field value
func (o *OperatorApprove) GetIntentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntentId
}

// GetIntentIdOk returns a tuple with the IntentId field value
// and a boolean to check if the value has been set.
func (o *OperatorApprove) GetIntentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntentId, true
}

// SetIntentId sets field value
func (o *OperatorApprove) SetIntentId(v string) {
	o.IntentId = v
}

// GetChallenge returns the Challenge field value
func (o *OperatorApprove) GetChallenge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Challenge
}

// GetChallengeOk returns a tuple with the Challenge field value
// and a boolean to check if the value has been set.
func (o *OperatorApprove) GetChallengeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Challenge, true
}

// SetChallenge sets field value
func (o *OperatorApprove) SetChallenge(v string) {
	o.Challenge = v
}

// GetMandateId returns the MandateId field value
func (o *OperatorApprove) GetMandateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MandateId
}

// GetMandateIdOk returns a tuple with the MandateId field value
// and a boolean to check if the value has been set.
func (o *OperatorApprove) GetMandateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MandateId, true
}

// SetMandateId sets field value
func (o *OperatorApprove) SetMandateId(v string) {
	o.MandateId = v
}

// GetRationale returns the Rationale field value
func (o *OperatorApprove) GetRationale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rationale
}

// GetRationaleOk returns a tuple with the Rationale field value
// and a boolean to check if the value has been set.
func (o *OperatorApprove) GetRationaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rationale, true
}

// SetRationale sets field value
func (o *OperatorApprove) SetRationale(v string) {
	o.Rationale = v
}

// GetAcknowledged returns the Acknowledged field value
func (o *OperatorApprove) GetAcknowledged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Acknowledged
}

// GetAcknowledgedOk returns a tuple with the Acknowledged field value
// and a boolean to check if the value has been set.
func (o *OperatorApprove) GetAcknowledgedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Acknowledged, true
}

// SetAcknowledged sets field value
func (o *OperatorApprove) SetAcknowledged(v bool) {
	o.Acknowledged = v
}

func (o OperatorApprove) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorApprove) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["intent_id"] = o.IntentId
	toSerialize["challenge"] = o.Challenge
	toSerialize["mandate_id"] = o.MandateId
	toSerialize["rationale"] = o.Rationale
	toSerialize["acknowledged"] = o.Acknowledged
	return toSerialize, nil
}

func (o *OperatorApprove) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"intent_id",
		"challenge",
		"mandate_id",
		"rationale",
		"acknowledged",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperatorApprove := _OperatorApprove{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperatorApprove)

	if err != nil {
		return err
	}

	*o = OperatorApprove(varOperatorApprove)

	return err
}

type NullableOperatorApprove struct {
	value *OperatorApprove
	isSet bool
}

func (v NullableOperatorApprove) Get() *OperatorApprove {
	return v.value
}

func (v *NullableOperatorApprove) Set(val *OperatorApprove) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorApprove) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorApprove) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorApprove(val *OperatorApprove) *NullableOperatorApprove {
	return &NullableOperatorApprove{value: val, isSet: true}
}

func (v NullableOperatorApprove) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorApprove) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


