/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the RememberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RememberRequest{}

// RememberRequest A gated memory write. The mandate needs `canWrite`.
type RememberRequest struct {
	Mandate MemoryMandate `json:"mandate"`
	Body interface{} `json:"body,omitempty"`
	ValidFrom time.Time `json:"validFrom"`
	ValidTo NullableTime `json:"validTo"`
	Edges []RememberRequestEdgesInner `json:"edges,omitempty"`
	Source string `json:"source"`
}

type _RememberRequest RememberRequest

// NewRememberRequest instantiates a new RememberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRememberRequest(mandate MemoryMandate, validFrom time.Time, validTo NullableTime, source string) *RememberRequest {
	this := RememberRequest{}
	this.Mandate = mandate
	this.ValidFrom = validFrom
	this.ValidTo = validTo
	this.Source = source
	return &this
}

// NewRememberRequestWithDefaults instantiates a new RememberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRememberRequestWithDefaults() *RememberRequest {
	this := RememberRequest{}
	return &this
}

// GetMandate returns the Mandate field value
func (o *RememberRequest) GetMandate() MemoryMandate {
	if o == nil {
		var ret MemoryMandate
		return ret
	}

	return o.Mandate
}

// GetMandateOk returns a tuple with the Mandate field value
// and a boolean to check if the value has been set.
func (o *RememberRequest) GetMandateOk() (*MemoryMandate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mandate, true
}

// SetMandate sets field value
func (o *RememberRequest) SetMandate(v MemoryMandate) {
	o.Mandate = v
}

// GetBody returns the Body field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RememberRequest) GetBody() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RememberRequest) GetBodyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return &o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *RememberRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given interface{} and assigns it to the Body field.
func (o *RememberRequest) SetBody(v interface{}) {
	o.Body = v
}

// GetValidFrom returns the ValidFrom field value
func (o *RememberRequest) GetValidFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value
// and a boolean to check if the value has been set.
func (o *RememberRequest) GetValidFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidFrom, true
}

// SetValidFrom sets field value
func (o *RememberRequest) SetValidFrom(v time.Time) {
	o.ValidFrom = v
}

// GetValidTo returns the ValidTo field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *RememberRequest) GetValidTo() time.Time {
	if o == nil || o.ValidTo.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ValidTo.Get()
}

// GetValidToOk returns a tuple with the ValidTo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RememberRequest) GetValidToOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValidTo.Get(), o.ValidTo.IsSet()
}

// SetValidTo sets field value
func (o *RememberRequest) SetValidTo(v time.Time) {
	o.ValidTo.Set(&v)
}

// GetEdges returns the Edges field value if set, zero value otherwise.
func (o *RememberRequest) GetEdges() []RememberRequestEdgesInner {
	if o == nil || IsNil(o.Edges) {
		var ret []RememberRequestEdgesInner
		return ret
	}
	return o.Edges
}

// GetEdgesOk returns a tuple with the Edges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RememberRequest) GetEdgesOk() ([]RememberRequestEdgesInner, bool) {
	if o == nil || IsNil(o.Edges) {
		return nil, false
	}
	return o.Edges, true
}

// HasEdges returns a boolean if a field has been set.
func (o *RememberRequest) HasEdges() bool {
	if o != nil && !IsNil(o.Edges) {
		return true
	}

	return false
}

// SetEdges gets a reference to the given []RememberRequestEdgesInner and assigns it to the Edges field.
func (o *RememberRequest) SetEdges(v []RememberRequestEdgesInner) {
	o.Edges = v
}

// GetSource returns the Source field value
func (o *RememberRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *RememberRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *RememberRequest) SetSource(v string) {
	o.Source = v
}

func (o RememberRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RememberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mandate"] = o.Mandate
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	toSerialize["validFrom"] = o.ValidFrom
	toSerialize["validTo"] = o.ValidTo.Get()
	if !IsNil(o.Edges) {
		toSerialize["edges"] = o.Edges
	}
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *RememberRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mandate",
		"validFrom",
		"validTo",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRememberRequest := _RememberRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRememberRequest)

	if err != nil {
		return err
	}

	*o = RememberRequest(varRememberRequest)

	return err
}

type NullableRememberRequest struct {
	value *RememberRequest
	isSet bool
}

func (v NullableRememberRequest) Get() *RememberRequest {
	return v.value
}

func (v *NullableRememberRequest) Set(val *RememberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRememberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRememberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRememberRequest(val *RememberRequest) *NullableRememberRequest {
	return &NullableRememberRequest{value: val, isSet: true}
}

func (v NullableRememberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRememberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


