/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SnapshotPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnapshotPage{}

// SnapshotPage struct for SnapshotPage
type SnapshotPage struct {
	Data []MemoryRecord `json:"data"`
	// True when items remain after this page.
	HasMore bool `json:"has_more"`
	// Token for the next page, or null when `has_more` is false.
	NextCursor string `json:"next_cursor"`
	ValidAt time.Time `json:"validAt"`
	TxAt time.Time `json:"txAt"`
	Seal Seal `json:"seal"`
}

type _SnapshotPage SnapshotPage

// NewSnapshotPage instantiates a new SnapshotPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnapshotPage(data []MemoryRecord, hasMore bool, nextCursor string, validAt time.Time, txAt time.Time, seal Seal) *SnapshotPage {
	this := SnapshotPage{}
	this.Data = data
	this.HasMore = hasMore
	this.NextCursor = nextCursor
	this.ValidAt = validAt
	this.TxAt = txAt
	this.Seal = seal
	return &this
}

// NewSnapshotPageWithDefaults instantiates a new SnapshotPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnapshotPageWithDefaults() *SnapshotPage {
	this := SnapshotPage{}
	return &this
}

// GetData returns the Data field value
func (o *SnapshotPage) GetData() []MemoryRecord {
	if o == nil {
		var ret []MemoryRecord
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SnapshotPage) GetDataOk() ([]MemoryRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SnapshotPage) SetData(v []MemoryRecord) {
	o.Data = v
}

// GetHasMore returns the HasMore field value
func (o *SnapshotPage) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *SnapshotPage) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *SnapshotPage) SetHasMore(v bool) {
	o.HasMore = v
}

// GetNextCursor returns the NextCursor field value
func (o *SnapshotPage) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *SnapshotPage) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *SnapshotPage) SetNextCursor(v string) {
	o.NextCursor = v
}

// GetValidAt returns the ValidAt field value
func (o *SnapshotPage) GetValidAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValidAt
}

// GetValidAtOk returns a tuple with the ValidAt field value
// and a boolean to check if the value has been set.
func (o *SnapshotPage) GetValidAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidAt, true
}

// SetValidAt sets field value
func (o *SnapshotPage) SetValidAt(v time.Time) {
	o.ValidAt = v
}

// GetTxAt returns the TxAt field value
func (o *SnapshotPage) GetTxAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.TxAt
}

// GetTxAtOk returns a tuple with the TxAt field value
// and a boolean to check if the value has been set.
func (o *SnapshotPage) GetTxAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxAt, true
}

// SetTxAt sets field value
func (o *SnapshotPage) SetTxAt(v time.Time) {
	o.TxAt = v
}

// GetSeal returns the Seal field value
func (o *SnapshotPage) GetSeal() Seal {
	if o == nil {
		var ret Seal
		return ret
	}

	return o.Seal
}

// GetSealOk returns a tuple with the Seal field value
// and a boolean to check if the value has been set.
func (o *SnapshotPage) GetSealOk() (*Seal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seal, true
}

// SetSeal sets field value
func (o *SnapshotPage) SetSeal(v Seal) {
	o.Seal = v
}

func (o SnapshotPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnapshotPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["has_more"] = o.HasMore
	toSerialize["next_cursor"] = o.NextCursor
	toSerialize["validAt"] = o.ValidAt
	toSerialize["txAt"] = o.TxAt
	toSerialize["seal"] = o.Seal
	return toSerialize, nil
}

func (o *SnapshotPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"has_more",
		"next_cursor",
		"validAt",
		"txAt",
		"seal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnapshotPage := _SnapshotPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSnapshotPage)

	if err != nil {
		return err
	}

	*o = SnapshotPage(varSnapshotPage)

	return err
}

type NullableSnapshotPage struct {
	value *SnapshotPage
	isSet bool
}

func (v NullableSnapshotPage) Get() *SnapshotPage {
	return v.value
}

func (v *NullableSnapshotPage) Set(val *SnapshotPage) {
	v.value = val
	v.isSet = true
}

func (v NullableSnapshotPage) IsSet() bool {
	return v.isSet
}

func (v *NullableSnapshotPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnapshotPage(val *SnapshotPage) *NullableSnapshotPage {
	return &NullableSnapshotPage{value: val, isSet: true}
}

func (v NullableSnapshotPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnapshotPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


