/*
General Liquidity — The Machine Economy API

General Liquidity (GL) is the governed, unified interface for the machine economy. A caller submits a signed `Intent`; the sovereign gate decides and only the server holds the settle primitive — the caller never reaches it (DESIGN §7, sovereign settle-separation).  This document is the **single source of truth** for the GL surface. The typed SDK (`packages/sdk`) and the MCP server (`packages/mcp`) are generated projections of this spec via Speakeasy (BUILD-PLAN §5).  Naming is canonical per `docs/NAMING.md`: verbs are single common English words (`resolve`, `pay`, `verify`, `disclose`, `buy`, `quote`); nouns are concrete singular domain objects (`Intent`, `Mandate`, `Receipt`, `Counterparty`). The wire is `snake_case`; the TypeScript SDK presents `camelCase`. Vendor/protocol names appear only as lowercase `RailId` values, never as verbs or types. 

API version: 2026-07-22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// Outcome The gate's verdict. Deny-first.
type Outcome string

// List of Outcome
const (
	ALLOW Outcome = "allow"
	CONFIRM Outcome = "confirm"
	DENY Outcome = "deny"
)

// All allowed values of Outcome enum
var AllowedOutcomeEnumValues = []Outcome{
	"allow",
	"confirm",
	"deny",
}

func (v *Outcome) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Outcome(value)
	for _, existing := range AllowedOutcomeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Outcome", value)
}

// NewOutcomeFromValue returns a pointer to a valid Outcome
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOutcomeFromValue(v string) (*Outcome, error) {
	ev := Outcome(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Outcome: valid values are %v", v, AllowedOutcomeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Outcome) IsValid() bool {
	for _, existing := range AllowedOutcomeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Outcome value
func (v Outcome) Ptr() *Outcome {
	return &v
}

type NullableOutcome struct {
	value *Outcome
	isSet bool
}

func (v NullableOutcome) Get() *Outcome {
	return v.value
}

func (v *NullableOutcome) Set(val *Outcome) {
	v.value = val
	v.isSet = true
}

func (v NullableOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullableOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutcome(val *Outcome) *NullableOutcome {
	return &NullableOutcome{value: val, isSet: true}
}

func (v NullableOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

