/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// CapitalSource Who fronts capital across the settlement.
type CapitalSource string

// List of CapitalSource
const (
	PAYER CapitalSource = "payer"
	FACILITATOR CapitalSource = "facilitator"
	MERCHANT_OF_RECORD CapitalSource = "merchant_of_record"
	SOLVER CapitalSource = "solver"
)

// All allowed values of CapitalSource enum
var AllowedCapitalSourceEnumValues = []CapitalSource{
	"payer",
	"facilitator",
	"merchant_of_record",
	"solver",
}

func (v *CapitalSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CapitalSource(value)
	for _, existing := range AllowedCapitalSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CapitalSource", value)
}

// NewCapitalSourceFromValue returns a pointer to a valid CapitalSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCapitalSourceFromValue(v string) (*CapitalSource, error) {
	ev := CapitalSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CapitalSource: valid values are %v", v, AllowedCapitalSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CapitalSource) IsValid() bool {
	for _, existing := range AllowedCapitalSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CapitalSource value
func (v CapitalSource) Ptr() *CapitalSource {
	return &v
}

type NullableCapitalSource struct {
	value *CapitalSource
	isSet bool
}

func (v NullableCapitalSource) Get() *CapitalSource {
	return v.value
}

func (v *NullableCapitalSource) Set(val *CapitalSource) {
	v.value = val
	v.isSet = true
}

func (v NullableCapitalSource) IsSet() bool {
	return v.isSet
}

func (v *NullableCapitalSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapitalSource(val *CapitalSource) *NullableCapitalSource {
	return &NullableCapitalSource{value: val, isSet: true}
}

func (v NullableCapitalSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapitalSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

