/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Snapshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Snapshot{}

// Snapshot A point-in-time snapshot — the records valid at `validAt`/`txAt`, under one seal.
type Snapshot struct {
	Records []MemoryRecord `json:"records"`
	ValidAt time.Time `json:"validAt"`
	TxAt time.Time `json:"txAt"`
	Seal Seal `json:"seal"`
}

type _Snapshot Snapshot

// NewSnapshot instantiates a new Snapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnapshot(records []MemoryRecord, validAt time.Time, txAt time.Time, seal Seal) *Snapshot {
	this := Snapshot{}
	this.Records = records
	this.ValidAt = validAt
	this.TxAt = txAt
	this.Seal = seal
	return &this
}

// NewSnapshotWithDefaults instantiates a new Snapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnapshotWithDefaults() *Snapshot {
	this := Snapshot{}
	return &this
}

// GetRecords returns the Records field value
func (o *Snapshot) GetRecords() []MemoryRecord {
	if o == nil {
		var ret []MemoryRecord
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
func (o *Snapshot) GetRecordsOk() ([]MemoryRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *Snapshot) SetRecords(v []MemoryRecord) {
	o.Records = v
}

// GetValidAt returns the ValidAt field value
func (o *Snapshot) GetValidAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValidAt
}

// GetValidAtOk returns a tuple with the ValidAt field value
// and a boolean to check if the value has been set.
func (o *Snapshot) GetValidAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidAt, true
}

// SetValidAt sets field value
func (o *Snapshot) SetValidAt(v time.Time) {
	o.ValidAt = v
}

// GetTxAt returns the TxAt field value
func (o *Snapshot) GetTxAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.TxAt
}

// GetTxAtOk returns a tuple with the TxAt field value
// and a boolean to check if the value has been set.
func (o *Snapshot) GetTxAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxAt, true
}

// SetTxAt sets field value
func (o *Snapshot) SetTxAt(v time.Time) {
	o.TxAt = v
}

// GetSeal returns the Seal field value
func (o *Snapshot) GetSeal() Seal {
	if o == nil {
		var ret Seal
		return ret
	}

	return o.Seal
}

// GetSealOk returns a tuple with the Seal field value
// and a boolean to check if the value has been set.
func (o *Snapshot) GetSealOk() (*Seal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seal, true
}

// SetSeal sets field value
func (o *Snapshot) SetSeal(v Seal) {
	o.Seal = v
}

func (o Snapshot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Snapshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["records"] = o.Records
	toSerialize["validAt"] = o.ValidAt
	toSerialize["txAt"] = o.TxAt
	toSerialize["seal"] = o.Seal
	return toSerialize, nil
}

func (o *Snapshot) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
		"validAt",
		"txAt",
		"seal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnapshot := _Snapshot{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSnapshot)

	if err != nil {
		return err
	}

	*o = Snapshot(varSnapshot)

	return err
}

type NullableSnapshot struct {
	value *Snapshot
	isSet bool
}

func (v NullableSnapshot) Get() *Snapshot {
	return v.value
}

func (v *NullableSnapshot) Set(val *Snapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnapshot(val *Snapshot) *NullableSnapshot {
	return &NullableSnapshot{value: val, isSet: true}
}

func (v NullableSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


