/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// Reversibility the model 'Reversibility'
type Reversibility string

// List of Reversibility
const (
	REVERSIBLE Reversibility = "reversible"
	IRREVERSIBLE Reversibility = "irreversible"
)

// All allowed values of Reversibility enum
var AllowedReversibilityEnumValues = []Reversibility{
	"reversible",
	"irreversible",
}

func (v *Reversibility) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Reversibility(value)
	for _, existing := range AllowedReversibilityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Reversibility", value)
}

// NewReversibilityFromValue returns a pointer to a valid Reversibility
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReversibilityFromValue(v string) (*Reversibility, error) {
	ev := Reversibility(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Reversibility: valid values are %v", v, AllowedReversibilityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Reversibility) IsValid() bool {
	for _, existing := range AllowedReversibilityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Reversibility value
func (v Reversibility) Ptr() *Reversibility {
	return &v
}

type NullableReversibility struct {
	value *Reversibility
	isSet bool
}

func (v NullableReversibility) Get() *Reversibility {
	return v.value
}

func (v *NullableReversibility) Set(val *Reversibility) {
	v.value = val
	v.isSet = true
}

func (v NullableReversibility) IsSet() bool {
	return v.isSet
}

func (v *NullableReversibility) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReversibility(val *Reversibility) *NullableReversibility {
	return &NullableReversibility{value: val, isSet: true}
}

func (v NullableReversibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReversibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

