/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// checks if the MemoryVerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryVerifyRequest{}

// MemoryVerifyRequest struct for MemoryVerifyRequest
type MemoryVerifyRequest struct {
	// A signed memory artifact to verify.
	Artifact interface{} `json:"artifact"`
	AdditionalProperties map[string]interface{}
}

type _MemoryVerifyRequest MemoryVerifyRequest

// NewMemoryVerifyRequest instantiates a new MemoryVerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryVerifyRequest(artifact interface{}) *MemoryVerifyRequest {
	this := MemoryVerifyRequest{}
	this.Artifact = artifact
	return &this
}

// NewMemoryVerifyRequestWithDefaults instantiates a new MemoryVerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryVerifyRequestWithDefaults() *MemoryVerifyRequest {
	this := MemoryVerifyRequest{}
	return &this
}

// GetArtifact returns the Artifact field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *MemoryVerifyRequest) GetArtifact() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Artifact
}

// GetArtifactOk returns a tuple with the Artifact field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryVerifyRequest) GetArtifactOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Artifact) {
		return nil, false
	}
	return &o.Artifact, true
}

// SetArtifact sets field value
func (o *MemoryVerifyRequest) SetArtifact(v interface{}) {
	o.Artifact = v
}

func (o MemoryVerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryVerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Artifact != nil {
		toSerialize["artifact"] = o.Artifact
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MemoryVerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"artifact",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryVerifyRequest := _MemoryVerifyRequest{}

	err = json.Unmarshal(data, &varMemoryVerifyRequest)

	if err != nil {
		return err
	}

	*o = MemoryVerifyRequest(varMemoryVerifyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "artifact")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMemoryVerifyRequest struct {
	value *MemoryVerifyRequest
	isSet bool
}

func (v NullableMemoryVerifyRequest) Get() *MemoryVerifyRequest {
	return v.value
}

func (v *NullableMemoryVerifyRequest) Set(val *MemoryVerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryVerifyRequest(val *MemoryVerifyRequest) *NullableMemoryVerifyRequest {
	return &NullableMemoryVerifyRequest{value: val, isSet: true}
}

func (v NullableMemoryVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


