/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"fmt"
)

// checks if the QuoteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteRequest{}

// QuoteRequest struct for QuoteRequest
type QuoteRequest struct {
	// Merchant reference / product query.
	What string `json:"what"`
	Constraints map[string]interface{} `json:"constraints,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _QuoteRequest QuoteRequest

// NewQuoteRequest instantiates a new QuoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteRequest(what string) *QuoteRequest {
	this := QuoteRequest{}
	this.What = what
	return &this
}

// NewQuoteRequestWithDefaults instantiates a new QuoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteRequestWithDefaults() *QuoteRequest {
	this := QuoteRequest{}
	return &this
}

// GetWhat returns the What field value
func (o *QuoteRequest) GetWhat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.What
}

// GetWhatOk returns a tuple with the What field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetWhatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.What, true
}

// SetWhat sets field value
func (o *QuoteRequest) SetWhat(v string) {
	o.What = v
}

// GetConstraints returns the Constraints field value if set, zero value otherwise.
func (o *QuoteRequest) GetConstraints() map[string]interface{} {
	if o == nil || IsNil(o.Constraints) {
		var ret map[string]interface{}
		return ret
	}
	return o.Constraints
}

// GetConstraintsOk returns a tuple with the Constraints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetConstraintsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Constraints) {
		return map[string]interface{}{}, false
	}
	return o.Constraints, true
}

// HasConstraints returns a boolean if a field has been set.
func (o *QuoteRequest) HasConstraints() bool {
	if o != nil && !IsNil(o.Constraints) {
		return true
	}

	return false
}

// SetConstraints gets a reference to the given map[string]interface{} and assigns it to the Constraints field.
func (o *QuoteRequest) SetConstraints(v map[string]interface{}) {
	o.Constraints = v
}

func (o QuoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["what"] = o.What
	if !IsNil(o.Constraints) {
		toSerialize["constraints"] = o.Constraints
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QuoteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"what",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuoteRequest := _QuoteRequest{}

	err = json.Unmarshal(data, &varQuoteRequest)

	if err != nil {
		return err
	}

	*o = QuoteRequest(varQuoteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "what")
		delete(additionalProperties, "constraints")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuoteRequest struct {
	value *QuoteRequest
	isSet bool
}

func (v NullableQuoteRequest) Get() *QuoteRequest {
	return v.value
}

func (v *NullableQuoteRequest) Set(val *QuoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteRequest(val *QuoteRequest) *NullableQuoteRequest {
	return &NullableQuoteRequest{value: val, isSet: true}
}

func (v NullableQuoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


