/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Terms type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Terms{}

// Terms The six irreducible fields — explicit on every Intent and Receipt, never silently defaulted. This is what the Gate reasons over. 
type Terms struct {
	Reversibility Reversibility `json:"reversibility"`
	Finality Finality `json:"finality"`
	// Authorization model id, e.g. \"eip3009\" | \"vc-mandate\" | \"http-sig\".
	Credential string `json:"credential"`
	Rail RailId `json:"rail"`
	CapitalSource CapitalSource `json:"capital_source"`
	Presence Presence `json:"presence"`
}

type _Terms Terms

// NewTerms instantiates a new Terms object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerms(reversibility Reversibility, finality Finality, credential string, rail RailId, capitalSource CapitalSource, presence Presence) *Terms {
	this := Terms{}
	this.Reversibility = reversibility
	this.Finality = finality
	this.Credential = credential
	this.Rail = rail
	this.CapitalSource = capitalSource
	this.Presence = presence
	return &this
}

// NewTermsWithDefaults instantiates a new Terms object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTermsWithDefaults() *Terms {
	this := Terms{}
	return &this
}

// GetReversibility returns the Reversibility field value
func (o *Terms) GetReversibility() Reversibility {
	if o == nil {
		var ret Reversibility
		return ret
	}

	return o.Reversibility
}

// GetReversibilityOk returns a tuple with the Reversibility field value
// and a boolean to check if the value has been set.
func (o *Terms) GetReversibilityOk() (*Reversibility, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reversibility, true
}

// SetReversibility sets field value
func (o *Terms) SetReversibility(v Reversibility) {
	o.Reversibility = v
}

// GetFinality returns the Finality field value
func (o *Terms) GetFinality() Finality {
	if o == nil {
		var ret Finality
		return ret
	}

	return o.Finality
}

// GetFinalityOk returns a tuple with the Finality field value
// and a boolean to check if the value has been set.
func (o *Terms) GetFinalityOk() (*Finality, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Finality, true
}

// SetFinality sets field value
func (o *Terms) SetFinality(v Finality) {
	o.Finality = v
}

// GetCredential returns the Credential field value
func (o *Terms) GetCredential() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Credential
}

// GetCredentialOk returns a tuple with the Credential field value
// and a boolean to check if the value has been set.
func (o *Terms) GetCredentialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credential, true
}

// SetCredential sets field value
func (o *Terms) SetCredential(v string) {
	o.Credential = v
}

// GetRail returns the Rail field value
func (o *Terms) GetRail() RailId {
	if o == nil {
		var ret RailId
		return ret
	}

	return o.Rail
}

// GetRailOk returns a tuple with the Rail field value
// and a boolean to check if the value has been set.
func (o *Terms) GetRailOk() (*RailId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rail, true
}

// SetRail sets field value
func (o *Terms) SetRail(v RailId) {
	o.Rail = v
}

// GetCapitalSource returns the CapitalSource field value
func (o *Terms) GetCapitalSource() CapitalSource {
	if o == nil {
		var ret CapitalSource
		return ret
	}

	return o.CapitalSource
}

// GetCapitalSourceOk returns a tuple with the CapitalSource field value
// and a boolean to check if the value has been set.
func (o *Terms) GetCapitalSourceOk() (*CapitalSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapitalSource, true
}

// SetCapitalSource sets field value
func (o *Terms) SetCapitalSource(v CapitalSource) {
	o.CapitalSource = v
}

// GetPresence returns the Presence field value
func (o *Terms) GetPresence() Presence {
	if o == nil {
		var ret Presence
		return ret
	}

	return o.Presence
}

// GetPresenceOk returns a tuple with the Presence field value
// and a boolean to check if the value has been set.
func (o *Terms) GetPresenceOk() (*Presence, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Presence, true
}

// SetPresence sets field value
func (o *Terms) SetPresence(v Presence) {
	o.Presence = v
}

func (o Terms) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Terms) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reversibility"] = o.Reversibility
	toSerialize["finality"] = o.Finality
	toSerialize["credential"] = o.Credential
	toSerialize["rail"] = o.Rail
	toSerialize["capital_source"] = o.CapitalSource
	toSerialize["presence"] = o.Presence
	return toSerialize, nil
}

func (o *Terms) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reversibility",
		"finality",
		"credential",
		"rail",
		"capital_source",
		"presence",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTerms := _Terms{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTerms)

	if err != nil {
		return err
	}

	*o = Terms(varTerms)

	return err
}

type NullableTerms struct {
	value *Terms
	isSet bool
}

func (v NullableTerms) Get() *Terms {
	return v.value
}

func (v *NullableTerms) Set(val *Terms) {
	v.value = val
	v.isSet = true
}

func (v NullableTerms) IsSet() bool {
	return v.isSet
}

func (v *NullableTerms) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerms(val *Terms) *NullableTerms {
	return &NullableTerms{value: val, isSet: true}
}

func (v NullableTerms) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerms) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


