/*
General Liquidity: The Machine Economy API

General Liquidity (GL) is one governed surface over payment, commerce, identity, and provenance for the machine economy. A caller submits a signed `Intent`, a deny-first gate decides, and only the server holds the settle primitive, so the caller never does. The wire convention is `snake_case`. 

API version: 2026-07-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generalliquidity

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Receipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Receipt{}

// Receipt Durable, machine-parseable proof of settlement.
type Receipt struct {
	IntentKey string `json:"intent_key"`
	Rail RailId `json:"rail"`
	// Rail settlement reference / on-chain tx hash.
	Reference string `json:"reference"`
	Terms Terms `json:"terms"`
	SettledAt time.Time `json:"settled_at"`
	// Proof-of-Enforcement hash, byte-identical between emitter and verifier.
	Enforcement string `json:"enforcement"`
}

type _Receipt Receipt

// NewReceipt instantiates a new Receipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceipt(intentKey string, rail RailId, reference string, terms Terms, settledAt time.Time, enforcement string) *Receipt {
	this := Receipt{}
	this.IntentKey = intentKey
	this.Rail = rail
	this.Reference = reference
	this.Terms = terms
	this.SettledAt = settledAt
	this.Enforcement = enforcement
	return &this
}

// NewReceiptWithDefaults instantiates a new Receipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptWithDefaults() *Receipt {
	this := Receipt{}
	return &this
}

// GetIntentKey returns the IntentKey field value
func (o *Receipt) GetIntentKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntentKey
}

// GetIntentKeyOk returns a tuple with the IntentKey field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetIntentKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntentKey, true
}

// SetIntentKey sets field value
func (o *Receipt) SetIntentKey(v string) {
	o.IntentKey = v
}

// GetRail returns the Rail field value
func (o *Receipt) GetRail() RailId {
	if o == nil {
		var ret RailId
		return ret
	}

	return o.Rail
}

// GetRailOk returns a tuple with the Rail field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetRailOk() (*RailId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rail, true
}

// SetRail sets field value
func (o *Receipt) SetRail(v RailId) {
	o.Rail = v
}

// GetReference returns the Reference field value
func (o *Receipt) GetReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reference, true
}

// SetReference sets field value
func (o *Receipt) SetReference(v string) {
	o.Reference = v
}

// GetTerms returns the Terms field value
func (o *Receipt) GetTerms() Terms {
	if o == nil {
		var ret Terms
		return ret
	}

	return o.Terms
}

// GetTermsOk returns a tuple with the Terms field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetTermsOk() (*Terms, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Terms, true
}

// SetTerms sets field value
func (o *Receipt) SetTerms(v Terms) {
	o.Terms = v
}

// GetSettledAt returns the SettledAt field value
func (o *Receipt) GetSettledAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SettledAt
}

// GetSettledAtOk returns a tuple with the SettledAt field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetSettledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettledAt, true
}

// SetSettledAt sets field value
func (o *Receipt) SetSettledAt(v time.Time) {
	o.SettledAt = v
}

// GetEnforcement returns the Enforcement field value
func (o *Receipt) GetEnforcement() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Enforcement
}

// GetEnforcementOk returns a tuple with the Enforcement field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetEnforcementOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enforcement, true
}

// SetEnforcement sets field value
func (o *Receipt) SetEnforcement(v string) {
	o.Enforcement = v
}

func (o Receipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Receipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["intent_key"] = o.IntentKey
	toSerialize["rail"] = o.Rail
	toSerialize["reference"] = o.Reference
	toSerialize["terms"] = o.Terms
	toSerialize["settled_at"] = o.SettledAt
	toSerialize["enforcement"] = o.Enforcement
	return toSerialize, nil
}

func (o *Receipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"intent_key",
		"rail",
		"reference",
		"terms",
		"settled_at",
		"enforcement",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceipt := _Receipt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceipt)

	if err != nil {
		return err
	}

	*o = Receipt(varReceipt)

	return err
}

type NullableReceipt struct {
	value *Receipt
	isSet bool
}

func (v NullableReceipt) Get() *Receipt {
	return v.value
}

func (v *NullableReceipt) Set(val *Receipt) {
	v.value = val
	v.isSet = true
}

func (v NullableReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceipt(val *Receipt) *NullableReceipt {
	return &NullableReceipt{value: val, isSet: true}
}

func (v NullableReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


