/*
General Liquidity — The Machine Economy API

Testing GovernanceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package generalliquidity

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/general-liquidity/general-liquidity-go/client"
)

func Test_generalliquidity_GovernanceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GovernanceAPIService Audit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.GovernanceAPI.Audit(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
